<?php
/**
 * AudioSeparationApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Camb\Ai\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Camb\Ai\ApiException;
use Camb\Ai\Configuration;
use Camb\Ai\FormDataProcessor;
use Camb\Ai\HeaderSelector;
use Camb\Ai\ObjectSerializer;

/**
 * AudioSeparationApi Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AudioSeparationApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createAudioSeparationAudioSeparationPost' => [
            'multipart/form-data',
        ],
        'getAudioSeparationRunInfoAudioSeparationResultRunIdGet' => [
            'application/json',
        ],
        'getAudioSeparationRunsResultsAudioSeparationResultsPost' => [
            'application/json',
        ],
        'getAudioSeparationStatusAudioSeparationTaskIdGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createAudioSeparationAudioSeparationPost
     *
     * Create Audio Separation
     *
     * @param  int|null $run_id run_id (optional)
     * @param  string|null $traceparent traceparent (optional)
     * @param  \SplFileObject|null $media_file media_file (optional)
     * @param  string|null $project_name project_name (optional)
     * @param  string|null $project_description project_description (optional)
     * @param  int|null $folder_id folder_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAudioSeparationAudioSeparationPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Camb.ai\Model\OrchestratorPipelineCallResult|\Camb.ai\Model\HTTPValidationError
     */
    public function createAudioSeparationAudioSeparationPost($run_id = null, $traceparent = null, $media_file = null, $project_name = null, $project_description = null, $folder_id = null, string $contentType = self::contentTypes['createAudioSeparationAudioSeparationPost'][0])
    {
        list($response) = $this->createAudioSeparationAudioSeparationPostWithHttpInfo($run_id, $traceparent, $media_file, $project_name, $project_description, $folder_id, $contentType);
        return $response;
    }

    /**
     * Operation createAudioSeparationAudioSeparationPostWithHttpInfo
     *
     * Create Audio Separation
     *
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  \SplFileObject|null $media_file (optional)
     * @param  string|null $project_name (optional)
     * @param  string|null $project_description (optional)
     * @param  int|null $folder_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAudioSeparationAudioSeparationPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Camb.ai\Model\OrchestratorPipelineCallResult|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createAudioSeparationAudioSeparationPostWithHttpInfo($run_id = null, $traceparent = null, $media_file = null, $project_name = null, $project_description = null, $folder_id = null, string $contentType = self::contentTypes['createAudioSeparationAudioSeparationPost'][0])
    {
        $request = $this->createAudioSeparationAudioSeparationPostRequest($run_id, $traceparent, $media_file, $project_name, $project_description, $folder_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\OrchestratorPipelineCallResult',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Camb.ai\Model\OrchestratorPipelineCallResult',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\OrchestratorPipelineCallResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createAudioSeparationAudioSeparationPostAsync
     *
     * Create Audio Separation
     *
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  \SplFileObject|null $media_file (optional)
     * @param  string|null $project_name (optional)
     * @param  string|null $project_description (optional)
     * @param  int|null $folder_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAudioSeparationAudioSeparationPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAudioSeparationAudioSeparationPostAsync($run_id = null, $traceparent = null, $media_file = null, $project_name = null, $project_description = null, $folder_id = null, string $contentType = self::contentTypes['createAudioSeparationAudioSeparationPost'][0])
    {
        return $this->createAudioSeparationAudioSeparationPostAsyncWithHttpInfo($run_id, $traceparent, $media_file, $project_name, $project_description, $folder_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createAudioSeparationAudioSeparationPostAsyncWithHttpInfo
     *
     * Create Audio Separation
     *
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  \SplFileObject|null $media_file (optional)
     * @param  string|null $project_name (optional)
     * @param  string|null $project_description (optional)
     * @param  int|null $folder_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAudioSeparationAudioSeparationPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAudioSeparationAudioSeparationPostAsyncWithHttpInfo($run_id = null, $traceparent = null, $media_file = null, $project_name = null, $project_description = null, $folder_id = null, string $contentType = self::contentTypes['createAudioSeparationAudioSeparationPost'][0])
    {
        $returnType = '\Camb.ai\Model\OrchestratorPipelineCallResult';
        $request = $this->createAudioSeparationAudioSeparationPostRequest($run_id, $traceparent, $media_file, $project_name, $project_description, $folder_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createAudioSeparationAudioSeparationPost'
     *
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  \SplFileObject|null $media_file (optional)
     * @param  string|null $project_name (optional)
     * @param  string|null $project_description (optional)
     * @param  int|null $folder_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAudioSeparationAudioSeparationPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createAudioSeparationAudioSeparationPostRequest($run_id = null, $traceparent = null, $media_file = null, $project_name = null, $project_description = null, $folder_id = null, string $contentType = self::contentTypes['createAudioSeparationAudioSeparationPost'][0])
    {




        if ($project_name !== null && strlen($project_name) > 255) {
            throw new \InvalidArgumentException('invalid length for "$project_name" when calling AudioSeparationApi.createAudioSeparationAudioSeparationPost, must be smaller than or equal to 255.');
        }
        if ($project_name !== null && strlen($project_name) < 3) {
            throw new \InvalidArgumentException('invalid length for "$project_name" when calling AudioSeparationApi.createAudioSeparationAudioSeparationPost, must be bigger than or equal to 3.');
        }
        
        if ($project_description !== null && strlen($project_description) > 5000) {
            throw new \InvalidArgumentException('invalid length for "$project_description" when calling AudioSeparationApi.createAudioSeparationAudioSeparationPost, must be smaller than or equal to 5000.');
        }
        if ($project_description !== null && strlen($project_description) < 3) {
            throw new \InvalidArgumentException('invalid length for "$project_description" when calling AudioSeparationApi.createAudioSeparationAudioSeparationPost, must be bigger than or equal to 3.');
        }
        


        $resourcePath = '/audio-separation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($traceparent !== null) {
            $headerParams['traceparent'] = ObjectSerializer::toHeaderValue($traceparent);
        }


        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'media_file' => $media_file,
            'project_name' => $project_name,
            'project_description' => $project_description,
            'folder_id' => $folder_id,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAudioSeparationRunInfoAudioSeparationResultRunIdGet
     *
     * Get Audio Separation Run Info
     *
     * @param  int|null $run_id run_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationRunInfoAudioSeparationResultRunIdGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Camb.ai\Model\GetAudioSeparationResultOut|\Camb.ai\Model\HTTPValidationError
     */
    public function getAudioSeparationRunInfoAudioSeparationResultRunIdGet($run_id, string $contentType = self::contentTypes['getAudioSeparationRunInfoAudioSeparationResultRunIdGet'][0])
    {
        list($response) = $this->getAudioSeparationRunInfoAudioSeparationResultRunIdGetWithHttpInfo($run_id, $contentType);
        return $response;
    }

    /**
     * Operation getAudioSeparationRunInfoAudioSeparationResultRunIdGetWithHttpInfo
     *
     * Get Audio Separation Run Info
     *
     * @param  int|null $run_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationRunInfoAudioSeparationResultRunIdGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Camb.ai\Model\GetAudioSeparationResultOut|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAudioSeparationRunInfoAudioSeparationResultRunIdGetWithHttpInfo($run_id, string $contentType = self::contentTypes['getAudioSeparationRunInfoAudioSeparationResultRunIdGet'][0])
    {
        $request = $this->getAudioSeparationRunInfoAudioSeparationResultRunIdGetRequest($run_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\GetAudioSeparationResultOut',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Camb.ai\Model\GetAudioSeparationResultOut',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\GetAudioSeparationResultOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAudioSeparationRunInfoAudioSeparationResultRunIdGetAsync
     *
     * Get Audio Separation Run Info
     *
     * @param  int|null $run_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationRunInfoAudioSeparationResultRunIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAudioSeparationRunInfoAudioSeparationResultRunIdGetAsync($run_id, string $contentType = self::contentTypes['getAudioSeparationRunInfoAudioSeparationResultRunIdGet'][0])
    {
        return $this->getAudioSeparationRunInfoAudioSeparationResultRunIdGetAsyncWithHttpInfo($run_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAudioSeparationRunInfoAudioSeparationResultRunIdGetAsyncWithHttpInfo
     *
     * Get Audio Separation Run Info
     *
     * @param  int|null $run_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationRunInfoAudioSeparationResultRunIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAudioSeparationRunInfoAudioSeparationResultRunIdGetAsyncWithHttpInfo($run_id, string $contentType = self::contentTypes['getAudioSeparationRunInfoAudioSeparationResultRunIdGet'][0])
    {
        $returnType = '\Camb.ai\Model\GetAudioSeparationResultOut';
        $request = $this->getAudioSeparationRunInfoAudioSeparationResultRunIdGetRequest($run_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAudioSeparationRunInfoAudioSeparationResultRunIdGet'
     *
     * @param  int|null $run_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationRunInfoAudioSeparationResultRunIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAudioSeparationRunInfoAudioSeparationResultRunIdGetRequest($run_id, string $contentType = self::contentTypes['getAudioSeparationRunInfoAudioSeparationResultRunIdGet'][0])
    {

        // verify the required parameter 'run_id' is set
        if ($run_id === null || (is_array($run_id) && count($run_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $run_id when calling getAudioSeparationRunInfoAudioSeparationResultRunIdGet'
            );
        }


        $resourcePath = '/audio-separation-result/{run_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($run_id !== null) {
            $resourcePath = str_replace(
                '{' . 'run_id' . '}',
                ObjectSerializer::toPathValue($run_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAudioSeparationRunsResultsAudioSeparationResultsPost
     *
     * Get Audio Separation Runs Results
     *
     * @param  \Camb.ai\Model\RunIDsRequestPayload $run_ids_request_payload run_ids_request_payload (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string|null $traceparent traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationRunsResultsAudioSeparationResultsPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array<string,\Camb.ai\Model\GetAudioSeparationResultOut>|\Camb.ai\Model\HTTPValidationError
     */
    public function getAudioSeparationRunsResultsAudioSeparationResultsPost($run_ids_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getAudioSeparationRunsResultsAudioSeparationResultsPost'][0])
    {
        list($response) = $this->getAudioSeparationRunsResultsAudioSeparationResultsPostWithHttpInfo($run_ids_request_payload, $run_id, $traceparent, $contentType);
        return $response;
    }

    /**
     * Operation getAudioSeparationRunsResultsAudioSeparationResultsPostWithHttpInfo
     *
     * Get Audio Separation Runs Results
     *
     * @param  \Camb.ai\Model\RunIDsRequestPayload $run_ids_request_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationRunsResultsAudioSeparationResultsPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of array<string,\Camb.ai\Model\GetAudioSeparationResultOut>|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAudioSeparationRunsResultsAudioSeparationResultsPostWithHttpInfo($run_ids_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getAudioSeparationRunsResultsAudioSeparationResultsPost'][0])
    {
        $request = $this->getAudioSeparationRunsResultsAudioSeparationResultsPostRequest($run_ids_request_payload, $run_id, $traceparent, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'array<string,\Camb.ai\Model\GetAudioSeparationResultOut>',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'array<string,\Camb.ai\Model\GetAudioSeparationResultOut>',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,\Camb.ai\Model\GetAudioSeparationResultOut>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAudioSeparationRunsResultsAudioSeparationResultsPostAsync
     *
     * Get Audio Separation Runs Results
     *
     * @param  \Camb.ai\Model\RunIDsRequestPayload $run_ids_request_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationRunsResultsAudioSeparationResultsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAudioSeparationRunsResultsAudioSeparationResultsPostAsync($run_ids_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getAudioSeparationRunsResultsAudioSeparationResultsPost'][0])
    {
        return $this->getAudioSeparationRunsResultsAudioSeparationResultsPostAsyncWithHttpInfo($run_ids_request_payload, $run_id, $traceparent, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAudioSeparationRunsResultsAudioSeparationResultsPostAsyncWithHttpInfo
     *
     * Get Audio Separation Runs Results
     *
     * @param  \Camb.ai\Model\RunIDsRequestPayload $run_ids_request_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationRunsResultsAudioSeparationResultsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAudioSeparationRunsResultsAudioSeparationResultsPostAsyncWithHttpInfo($run_ids_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getAudioSeparationRunsResultsAudioSeparationResultsPost'][0])
    {
        $returnType = 'array<string,\Camb.ai\Model\GetAudioSeparationResultOut>';
        $request = $this->getAudioSeparationRunsResultsAudioSeparationResultsPostRequest($run_ids_request_payload, $run_id, $traceparent, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAudioSeparationRunsResultsAudioSeparationResultsPost'
     *
     * @param  \Camb.ai\Model\RunIDsRequestPayload $run_ids_request_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationRunsResultsAudioSeparationResultsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAudioSeparationRunsResultsAudioSeparationResultsPostRequest($run_ids_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getAudioSeparationRunsResultsAudioSeparationResultsPost'][0])
    {

        // verify the required parameter 'run_ids_request_payload' is set
        if ($run_ids_request_payload === null || (is_array($run_ids_request_payload) && count($run_ids_request_payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $run_ids_request_payload when calling getAudioSeparationRunsResultsAudioSeparationResultsPost'
            );
        }




        $resourcePath = '/audio-separation-results';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($traceparent !== null) {
            $headerParams['traceparent'] = ObjectSerializer::toHeaderValue($traceparent);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($run_ids_request_payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($run_ids_request_payload));
            } else {
                $httpBody = $run_ids_request_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAudioSeparationStatusAudioSeparationTaskIdGet
     *
     * Get Audio Separation Status
     *
     * @param  string $task_id task_id (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationStatusAudioSeparationTaskIdGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Camb.ai\Model\OrchestratorPipelineResult|\Camb.ai\Model\HTTPValidationError
     */
    public function getAudioSeparationStatusAudioSeparationTaskIdGet($task_id, $run_id = null, string $contentType = self::contentTypes['getAudioSeparationStatusAudioSeparationTaskIdGet'][0])
    {
        list($response) = $this->getAudioSeparationStatusAudioSeparationTaskIdGetWithHttpInfo($task_id, $run_id, $contentType);
        return $response;
    }

    /**
     * Operation getAudioSeparationStatusAudioSeparationTaskIdGetWithHttpInfo
     *
     * Get Audio Separation Status
     *
     * @param  string $task_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationStatusAudioSeparationTaskIdGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Camb.ai\Model\OrchestratorPipelineResult|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAudioSeparationStatusAudioSeparationTaskIdGetWithHttpInfo($task_id, $run_id = null, string $contentType = self::contentTypes['getAudioSeparationStatusAudioSeparationTaskIdGet'][0])
    {
        $request = $this->getAudioSeparationStatusAudioSeparationTaskIdGetRequest($task_id, $run_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\OrchestratorPipelineResult',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Camb.ai\Model\OrchestratorPipelineResult',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\OrchestratorPipelineResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAudioSeparationStatusAudioSeparationTaskIdGetAsync
     *
     * Get Audio Separation Status
     *
     * @param  string $task_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationStatusAudioSeparationTaskIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAudioSeparationStatusAudioSeparationTaskIdGetAsync($task_id, $run_id = null, string $contentType = self::contentTypes['getAudioSeparationStatusAudioSeparationTaskIdGet'][0])
    {
        return $this->getAudioSeparationStatusAudioSeparationTaskIdGetAsyncWithHttpInfo($task_id, $run_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAudioSeparationStatusAudioSeparationTaskIdGetAsyncWithHttpInfo
     *
     * Get Audio Separation Status
     *
     * @param  string $task_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationStatusAudioSeparationTaskIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAudioSeparationStatusAudioSeparationTaskIdGetAsyncWithHttpInfo($task_id, $run_id = null, string $contentType = self::contentTypes['getAudioSeparationStatusAudioSeparationTaskIdGet'][0])
    {
        $returnType = '\Camb.ai\Model\OrchestratorPipelineResult';
        $request = $this->getAudioSeparationStatusAudioSeparationTaskIdGetRequest($task_id, $run_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAudioSeparationStatusAudioSeparationTaskIdGet'
     *
     * @param  string $task_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAudioSeparationStatusAudioSeparationTaskIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAudioSeparationStatusAudioSeparationTaskIdGetRequest($task_id, $run_id = null, string $contentType = self::contentTypes['getAudioSeparationStatusAudioSeparationTaskIdGet'][0])
    {

        // verify the required parameter 'task_id' is set
        if ($task_id === null || (is_array($task_id) && count($task_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $task_id when calling getAudioSeparationStatusAudioSeparationTaskIdGet'
            );
        }



        $resourcePath = '/audio-separation/{task_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($task_id !== null) {
            $resourcePath = str_replace(
                '{' . 'task_id' . '}',
                ObjectSerializer::toPathValue($task_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
