<?php
/**
 * DeprecatedStreamingApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Camb\Ai\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Camb\Ai\ApiException;
use Camb\Ai\Configuration;
use Camb\Ai\FormDataProcessor;
use Camb\Ai\HeaderSelector;
use Camb\Ai\ObjectSerializer;

/**
 * DeprecatedStreamingApi Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeprecatedStreamingApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createStreamV1StreamPost' => [
            'application/json',
        ],
        'getProbeStreamV1StreamProbePost' => [
            'application/json',
        ],
        'getStreamResultV1StreamStreamIdGet' => [
            'application/json',
        ],
        'stopStreamV1StreamStreamIdStopGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createStreamV1StreamPost
     *
     * Create Stream
     *
     * @param  \Camb.ai\Model\CreateStreamRequestPayload $create_stream_request_payload create_stream_request_payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStreamV1StreamPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Camb.ai\Model\CreateStreamOut|\Camb.ai\Model\HTTPValidationError
     * @deprecated
     */
    public function createStreamV1StreamPost($create_stream_request_payload, string $contentType = self::contentTypes['createStreamV1StreamPost'][0])
    {
        list($response) = $this->createStreamV1StreamPostWithHttpInfo($create_stream_request_payload, $contentType);
        return $response;
    }

    /**
     * Operation createStreamV1StreamPostWithHttpInfo
     *
     * Create Stream
     *
     * @param  \Camb.ai\Model\CreateStreamRequestPayload $create_stream_request_payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStreamV1StreamPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Camb.ai\Model\CreateStreamOut|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     * @deprecated
     */
    public function createStreamV1StreamPostWithHttpInfo($create_stream_request_payload, string $contentType = self::contentTypes['createStreamV1StreamPost'][0])
    {
        $request = $this->createStreamV1StreamPostRequest($create_stream_request_payload, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\CreateStreamOut',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Camb.ai\Model\CreateStreamOut',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\CreateStreamOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createStreamV1StreamPostAsync
     *
     * Create Stream
     *
     * @param  \Camb.ai\Model\CreateStreamRequestPayload $create_stream_request_payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStreamV1StreamPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function createStreamV1StreamPostAsync($create_stream_request_payload, string $contentType = self::contentTypes['createStreamV1StreamPost'][0])
    {
        return $this->createStreamV1StreamPostAsyncWithHttpInfo($create_stream_request_payload, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createStreamV1StreamPostAsyncWithHttpInfo
     *
     * Create Stream
     *
     * @param  \Camb.ai\Model\CreateStreamRequestPayload $create_stream_request_payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStreamV1StreamPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function createStreamV1StreamPostAsyncWithHttpInfo($create_stream_request_payload, string $contentType = self::contentTypes['createStreamV1StreamPost'][0])
    {
        $returnType = '\Camb.ai\Model\CreateStreamOut';
        $request = $this->createStreamV1StreamPostRequest($create_stream_request_payload, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createStreamV1StreamPost'
     *
     * @param  \Camb.ai\Model\CreateStreamRequestPayload $create_stream_request_payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStreamV1StreamPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     * @deprecated
     */
    public function createStreamV1StreamPostRequest($create_stream_request_payload, string $contentType = self::contentTypes['createStreamV1StreamPost'][0])
    {

        // verify the required parameter 'create_stream_request_payload' is set
        if ($create_stream_request_payload === null || (is_array($create_stream_request_payload) && count($create_stream_request_payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_stream_request_payload when calling createStreamV1StreamPost'
            );
        }


        $resourcePath = '/v1/stream';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_stream_request_payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_stream_request_payload));
            } else {
                $httpBody = $create_stream_request_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getProbeStreamV1StreamProbePost
     *
     * Get Probe Stream
     *
     * @param  \Camb.ai\Model\GetProbeStreamIn $get_probe_stream_in get_probe_stream_in (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string|null $traceparent traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProbeStreamV1StreamProbePost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Camb.ai\Model\GetProbeStreamOut|\Camb.ai\Model\HTTPValidationError
     * @deprecated
     */
    public function getProbeStreamV1StreamProbePost($get_probe_stream_in, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getProbeStreamV1StreamProbePost'][0])
    {
        list($response) = $this->getProbeStreamV1StreamProbePostWithHttpInfo($get_probe_stream_in, $run_id, $traceparent, $contentType);
        return $response;
    }

    /**
     * Operation getProbeStreamV1StreamProbePostWithHttpInfo
     *
     * Get Probe Stream
     *
     * @param  \Camb.ai\Model\GetProbeStreamIn $get_probe_stream_in (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProbeStreamV1StreamProbePost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Camb.ai\Model\GetProbeStreamOut|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     * @deprecated
     */
    public function getProbeStreamV1StreamProbePostWithHttpInfo($get_probe_stream_in, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getProbeStreamV1StreamProbePost'][0])
    {
        $request = $this->getProbeStreamV1StreamProbePostRequest($get_probe_stream_in, $run_id, $traceparent, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\GetProbeStreamOut',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Camb.ai\Model\GetProbeStreamOut',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\GetProbeStreamOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getProbeStreamV1StreamProbePostAsync
     *
     * Get Probe Stream
     *
     * @param  \Camb.ai\Model\GetProbeStreamIn $get_probe_stream_in (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProbeStreamV1StreamProbePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function getProbeStreamV1StreamProbePostAsync($get_probe_stream_in, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getProbeStreamV1StreamProbePost'][0])
    {
        return $this->getProbeStreamV1StreamProbePostAsyncWithHttpInfo($get_probe_stream_in, $run_id, $traceparent, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProbeStreamV1StreamProbePostAsyncWithHttpInfo
     *
     * Get Probe Stream
     *
     * @param  \Camb.ai\Model\GetProbeStreamIn $get_probe_stream_in (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProbeStreamV1StreamProbePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function getProbeStreamV1StreamProbePostAsyncWithHttpInfo($get_probe_stream_in, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getProbeStreamV1StreamProbePost'][0])
    {
        $returnType = '\Camb.ai\Model\GetProbeStreamOut';
        $request = $this->getProbeStreamV1StreamProbePostRequest($get_probe_stream_in, $run_id, $traceparent, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProbeStreamV1StreamProbePost'
     *
     * @param  \Camb.ai\Model\GetProbeStreamIn $get_probe_stream_in (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getProbeStreamV1StreamProbePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     * @deprecated
     */
    public function getProbeStreamV1StreamProbePostRequest($get_probe_stream_in, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getProbeStreamV1StreamProbePost'][0])
    {

        // verify the required parameter 'get_probe_stream_in' is set
        if ($get_probe_stream_in === null || (is_array($get_probe_stream_in) && count($get_probe_stream_in) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $get_probe_stream_in when calling getProbeStreamV1StreamProbePost'
            );
        }




        $resourcePath = '/v1/stream/probe';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($traceparent !== null) {
            $headerParams['traceparent'] = ObjectSerializer::toHeaderValue($traceparent);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($get_probe_stream_in)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($get_probe_stream_in));
            } else {
                $httpBody = $get_probe_stream_in;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getStreamResultV1StreamStreamIdGet
     *
     * Get Stream Result
     *
     * @param  int $stream_id stream_id (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStreamResultV1StreamStreamIdGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array<string,mixed>|\Camb.ai\Model\HTTPValidationError
     * @deprecated
     */
    public function getStreamResultV1StreamStreamIdGet($stream_id, $run_id = null, string $contentType = self::contentTypes['getStreamResultV1StreamStreamIdGet'][0])
    {
        list($response) = $this->getStreamResultV1StreamStreamIdGetWithHttpInfo($stream_id, $run_id, $contentType);
        return $response;
    }

    /**
     * Operation getStreamResultV1StreamStreamIdGetWithHttpInfo
     *
     * Get Stream Result
     *
     * @param  int $stream_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStreamResultV1StreamStreamIdGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of array<string,mixed>|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     * @deprecated
     */
    public function getStreamResultV1StreamStreamIdGetWithHttpInfo($stream_id, $run_id = null, string $contentType = self::contentTypes['getStreamResultV1StreamStreamIdGet'][0])
    {
        $request = $this->getStreamResultV1StreamStreamIdGetRequest($stream_id, $run_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'array<string,mixed>',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getStreamResultV1StreamStreamIdGetAsync
     *
     * Get Stream Result
     *
     * @param  int $stream_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStreamResultV1StreamStreamIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function getStreamResultV1StreamStreamIdGetAsync($stream_id, $run_id = null, string $contentType = self::contentTypes['getStreamResultV1StreamStreamIdGet'][0])
    {
        return $this->getStreamResultV1StreamStreamIdGetAsyncWithHttpInfo($stream_id, $run_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getStreamResultV1StreamStreamIdGetAsyncWithHttpInfo
     *
     * Get Stream Result
     *
     * @param  int $stream_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStreamResultV1StreamStreamIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function getStreamResultV1StreamStreamIdGetAsyncWithHttpInfo($stream_id, $run_id = null, string $contentType = self::contentTypes['getStreamResultV1StreamStreamIdGet'][0])
    {
        $returnType = 'array<string,mixed>';
        $request = $this->getStreamResultV1StreamStreamIdGetRequest($stream_id, $run_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getStreamResultV1StreamStreamIdGet'
     *
     * @param  int $stream_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStreamResultV1StreamStreamIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     * @deprecated
     */
    public function getStreamResultV1StreamStreamIdGetRequest($stream_id, $run_id = null, string $contentType = self::contentTypes['getStreamResultV1StreamStreamIdGet'][0])
    {

        // verify the required parameter 'stream_id' is set
        if ($stream_id === null || (is_array($stream_id) && count($stream_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $stream_id when calling getStreamResultV1StreamStreamIdGet'
            );
        }



        $resourcePath = '/v1/stream/{stream_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($stream_id !== null) {
            $resourcePath = str_replace(
                '{' . 'stream_id' . '}',
                ObjectSerializer::toPathValue($stream_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation stopStreamV1StreamStreamIdStopGet
     *
     * Stop Stream
     *
     * @param  int $stream_id stream_id (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['stopStreamV1StreamStreamIdStopGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array<string,mixed>|\Camb.ai\Model\HTTPValidationError
     * @deprecated
     */
    public function stopStreamV1StreamStreamIdStopGet($stream_id, $run_id = null, string $contentType = self::contentTypes['stopStreamV1StreamStreamIdStopGet'][0])
    {
        list($response) = $this->stopStreamV1StreamStreamIdStopGetWithHttpInfo($stream_id, $run_id, $contentType);
        return $response;
    }

    /**
     * Operation stopStreamV1StreamStreamIdStopGetWithHttpInfo
     *
     * Stop Stream
     *
     * @param  int $stream_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['stopStreamV1StreamStreamIdStopGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of array<string,mixed>|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     * @deprecated
     */
    public function stopStreamV1StreamStreamIdStopGetWithHttpInfo($stream_id, $run_id = null, string $contentType = self::contentTypes['stopStreamV1StreamStreamIdStopGet'][0])
    {
        $request = $this->stopStreamV1StreamStreamIdStopGetRequest($stream_id, $run_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'array<string,mixed>',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation stopStreamV1StreamStreamIdStopGetAsync
     *
     * Stop Stream
     *
     * @param  int $stream_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['stopStreamV1StreamStreamIdStopGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function stopStreamV1StreamStreamIdStopGetAsync($stream_id, $run_id = null, string $contentType = self::contentTypes['stopStreamV1StreamStreamIdStopGet'][0])
    {
        return $this->stopStreamV1StreamStreamIdStopGetAsyncWithHttpInfo($stream_id, $run_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation stopStreamV1StreamStreamIdStopGetAsyncWithHttpInfo
     *
     * Stop Stream
     *
     * @param  int $stream_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['stopStreamV1StreamStreamIdStopGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function stopStreamV1StreamStreamIdStopGetAsyncWithHttpInfo($stream_id, $run_id = null, string $contentType = self::contentTypes['stopStreamV1StreamStreamIdStopGet'][0])
    {
        $returnType = 'array<string,mixed>';
        $request = $this->stopStreamV1StreamStreamIdStopGetRequest($stream_id, $run_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'stopStreamV1StreamStreamIdStopGet'
     *
     * @param  int $stream_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['stopStreamV1StreamStreamIdStopGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     * @deprecated
     */
    public function stopStreamV1StreamStreamIdStopGetRequest($stream_id, $run_id = null, string $contentType = self::contentTypes['stopStreamV1StreamStreamIdStopGet'][0])
    {

        // verify the required parameter 'stream_id' is set
        if ($stream_id === null || (is_array($stream_id) && count($stream_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $stream_id when calling stopStreamV1StreamStreamIdStopGet'
            );
        }



        $resourcePath = '/v1/stream/{stream_id}/stop';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($stream_id !== null) {
            $resourcePath = str_replace(
                '{' . 'stream_id' . '}',
                ObjectSerializer::toPathValue($stream_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
