<?php
/**
 * FoldersApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Camb\Ai\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Camb\Ai\ApiException;
use Camb\Ai\Configuration;
use Camb\Ai\FormDataProcessor;
use Camb\Ai\HeaderSelector;
use Camb\Ai\ObjectSerializer;

/**
 * FoldersApi Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FoldersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createFolderFoldersCreatePost' => [
            'application/json',
        ],
        'createFolderFoldersCreatePost_0' => [
            'application/json',
        ],
        'listFoldersFoldersGet' => [
            'application/json',
        ],
        'listFoldersFoldersGet_0' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createFolderFoldersCreatePost
     *
     * Create Folder
     *
     * @param  \Camb.ai\Model\CreateFolderPayload $create_folder_payload create_folder_payload (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createFolderFoldersCreatePost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return mixed|\Camb.ai\Model\HTTPValidationError
     */
    public function createFolderFoldersCreatePost($create_folder_payload, $run_id = null, string $contentType = self::contentTypes['createFolderFoldersCreatePost'][0])
    {
        list($response) = $this->createFolderFoldersCreatePostWithHttpInfo($create_folder_payload, $run_id, $contentType);
        return $response;
    }

    /**
     * Operation createFolderFoldersCreatePostWithHttpInfo
     *
     * Create Folder
     *
     * @param  \Camb.ai\Model\CreateFolderPayload $create_folder_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createFolderFoldersCreatePost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of mixed|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createFolderFoldersCreatePostWithHttpInfo($create_folder_payload, $run_id = null, string $contentType = self::contentTypes['createFolderFoldersCreatePost'][0])
    {
        $request = $this->createFolderFoldersCreatePostRequest($create_folder_payload, $run_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'mixed',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createFolderFoldersCreatePostAsync
     *
     * Create Folder
     *
     * @param  \Camb.ai\Model\CreateFolderPayload $create_folder_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createFolderFoldersCreatePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createFolderFoldersCreatePostAsync($create_folder_payload, $run_id = null, string $contentType = self::contentTypes['createFolderFoldersCreatePost'][0])
    {
        return $this->createFolderFoldersCreatePostAsyncWithHttpInfo($create_folder_payload, $run_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createFolderFoldersCreatePostAsyncWithHttpInfo
     *
     * Create Folder
     *
     * @param  \Camb.ai\Model\CreateFolderPayload $create_folder_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createFolderFoldersCreatePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createFolderFoldersCreatePostAsyncWithHttpInfo($create_folder_payload, $run_id = null, string $contentType = self::contentTypes['createFolderFoldersCreatePost'][0])
    {
        $returnType = 'mixed';
        $request = $this->createFolderFoldersCreatePostRequest($create_folder_payload, $run_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createFolderFoldersCreatePost'
     *
     * @param  \Camb.ai\Model\CreateFolderPayload $create_folder_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createFolderFoldersCreatePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createFolderFoldersCreatePostRequest($create_folder_payload, $run_id = null, string $contentType = self::contentTypes['createFolderFoldersCreatePost'][0])
    {

        // verify the required parameter 'create_folder_payload' is set
        if ($create_folder_payload === null || (is_array($create_folder_payload) && count($create_folder_payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_folder_payload when calling createFolderFoldersCreatePost'
            );
        }



        $resourcePath = '/folders/create';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_folder_payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_folder_payload));
            } else {
                $httpBody = $create_folder_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createFolderFoldersCreatePost_0
     *
     * Create Folder
     *
     * @param  \Camb.ai\Model\CreateFolderPayload $create_folder_payload create_folder_payload (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createFolderFoldersCreatePost_0'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return mixed|\Camb.ai\Model\HTTPValidationError
     */
    public function createFolderFoldersCreatePost_0($create_folder_payload, $run_id = null, string $contentType = self::contentTypes['createFolderFoldersCreatePost_0'][0])
    {
        list($response) = $this->createFolderFoldersCreatePost_0WithHttpInfo($create_folder_payload, $run_id, $contentType);
        return $response;
    }

    /**
     * Operation createFolderFoldersCreatePost_0WithHttpInfo
     *
     * Create Folder
     *
     * @param  \Camb.ai\Model\CreateFolderPayload $create_folder_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createFolderFoldersCreatePost_0'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of mixed|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createFolderFoldersCreatePost_0WithHttpInfo($create_folder_payload, $run_id = null, string $contentType = self::contentTypes['createFolderFoldersCreatePost_0'][0])
    {
        $request = $this->createFolderFoldersCreatePost_0Request($create_folder_payload, $run_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'mixed',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createFolderFoldersCreatePost_0Async
     *
     * Create Folder
     *
     * @param  \Camb.ai\Model\CreateFolderPayload $create_folder_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createFolderFoldersCreatePost_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createFolderFoldersCreatePost_0Async($create_folder_payload, $run_id = null, string $contentType = self::contentTypes['createFolderFoldersCreatePost_0'][0])
    {
        return $this->createFolderFoldersCreatePost_0AsyncWithHttpInfo($create_folder_payload, $run_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createFolderFoldersCreatePost_0AsyncWithHttpInfo
     *
     * Create Folder
     *
     * @param  \Camb.ai\Model\CreateFolderPayload $create_folder_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createFolderFoldersCreatePost_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createFolderFoldersCreatePost_0AsyncWithHttpInfo($create_folder_payload, $run_id = null, string $contentType = self::contentTypes['createFolderFoldersCreatePost_0'][0])
    {
        $returnType = 'mixed';
        $request = $this->createFolderFoldersCreatePost_0Request($create_folder_payload, $run_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createFolderFoldersCreatePost_0'
     *
     * @param  \Camb.ai\Model\CreateFolderPayload $create_folder_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createFolderFoldersCreatePost_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createFolderFoldersCreatePost_0Request($create_folder_payload, $run_id = null, string $contentType = self::contentTypes['createFolderFoldersCreatePost_0'][0])
    {

        // verify the required parameter 'create_folder_payload' is set
        if ($create_folder_payload === null || (is_array($create_folder_payload) && count($create_folder_payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_folder_payload when calling createFolderFoldersCreatePost_0'
            );
        }



        $resourcePath = '/folders/create';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_folder_payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_folder_payload));
            } else {
                $httpBody = $create_folder_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listFoldersFoldersGet
     *
     * List Folders
     *
     * @param  int|null $limit limit (optional)
     * @param  string|null $search_query search_query (optional)
     * @param  int|null $run_id run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFoldersFoldersGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Camb.ai\Model\Folder[]|\Camb.ai\Model\HTTPValidationError
     */
    public function listFoldersFoldersGet($limit = null, $search_query = null, $run_id = null, string $contentType = self::contentTypes['listFoldersFoldersGet'][0])
    {
        list($response) = $this->listFoldersFoldersGetWithHttpInfo($limit, $search_query, $run_id, $contentType);
        return $response;
    }

    /**
     * Operation listFoldersFoldersGetWithHttpInfo
     *
     * List Folders
     *
     * @param  int|null $limit (optional)
     * @param  string|null $search_query (optional)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFoldersFoldersGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Camb.ai\Model\Folder[]|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listFoldersFoldersGetWithHttpInfo($limit = null, $search_query = null, $run_id = null, string $contentType = self::contentTypes['listFoldersFoldersGet'][0])
    {
        $request = $this->listFoldersFoldersGetRequest($limit, $search_query, $run_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\Folder[]',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Camb.ai\Model\Folder[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\Folder[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listFoldersFoldersGetAsync
     *
     * List Folders
     *
     * @param  int|null $limit (optional)
     * @param  string|null $search_query (optional)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFoldersFoldersGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listFoldersFoldersGetAsync($limit = null, $search_query = null, $run_id = null, string $contentType = self::contentTypes['listFoldersFoldersGet'][0])
    {
        return $this->listFoldersFoldersGetAsyncWithHttpInfo($limit, $search_query, $run_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listFoldersFoldersGetAsyncWithHttpInfo
     *
     * List Folders
     *
     * @param  int|null $limit (optional)
     * @param  string|null $search_query (optional)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFoldersFoldersGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listFoldersFoldersGetAsyncWithHttpInfo($limit = null, $search_query = null, $run_id = null, string $contentType = self::contentTypes['listFoldersFoldersGet'][0])
    {
        $returnType = '\Camb.ai\Model\Folder[]';
        $request = $this->listFoldersFoldersGetRequest($limit, $search_query, $run_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listFoldersFoldersGet'
     *
     * @param  int|null $limit (optional)
     * @param  string|null $search_query (optional)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFoldersFoldersGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listFoldersFoldersGetRequest($limit = null, $search_query = null, $run_id = null, string $contentType = self::contentTypes['listFoldersFoldersGet'][0])
    {

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling FoldersApi.listFoldersFoldersGet, must be smaller than or equal to 100.');
        }
        
        if ($search_query !== null && strlen($search_query) > 255) {
            throw new \InvalidArgumentException('invalid length for "$search_query" when calling FoldersApi.listFoldersFoldersGet, must be smaller than or equal to 255.');
        }
        if ($search_query !== null && strlen($search_query) < 2) {
            throw new \InvalidArgumentException('invalid length for "$search_query" when calling FoldersApi.listFoldersFoldersGet, must be bigger than or equal to 2.');
        }
        


        $resourcePath = '/folders';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search_query,
            'search_query', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listFoldersFoldersGet_0
     *
     * List Folders
     *
     * @param  int|null $limit limit (optional)
     * @param  string|null $search_query search_query (optional)
     * @param  int|null $run_id run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFoldersFoldersGet_0'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Camb.ai\Model\Folder[]|\Camb.ai\Model\HTTPValidationError
     */
    public function listFoldersFoldersGet_0($limit = null, $search_query = null, $run_id = null, string $contentType = self::contentTypes['listFoldersFoldersGet_0'][0])
    {
        list($response) = $this->listFoldersFoldersGet_0WithHttpInfo($limit, $search_query, $run_id, $contentType);
        return $response;
    }

    /**
     * Operation listFoldersFoldersGet_0WithHttpInfo
     *
     * List Folders
     *
     * @param  int|null $limit (optional)
     * @param  string|null $search_query (optional)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFoldersFoldersGet_0'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Camb.ai\Model\Folder[]|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listFoldersFoldersGet_0WithHttpInfo($limit = null, $search_query = null, $run_id = null, string $contentType = self::contentTypes['listFoldersFoldersGet_0'][0])
    {
        $request = $this->listFoldersFoldersGet_0Request($limit, $search_query, $run_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\Folder[]',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Camb.ai\Model\Folder[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\Folder[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listFoldersFoldersGet_0Async
     *
     * List Folders
     *
     * @param  int|null $limit (optional)
     * @param  string|null $search_query (optional)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFoldersFoldersGet_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listFoldersFoldersGet_0Async($limit = null, $search_query = null, $run_id = null, string $contentType = self::contentTypes['listFoldersFoldersGet_0'][0])
    {
        return $this->listFoldersFoldersGet_0AsyncWithHttpInfo($limit, $search_query, $run_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listFoldersFoldersGet_0AsyncWithHttpInfo
     *
     * List Folders
     *
     * @param  int|null $limit (optional)
     * @param  string|null $search_query (optional)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFoldersFoldersGet_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listFoldersFoldersGet_0AsyncWithHttpInfo($limit = null, $search_query = null, $run_id = null, string $contentType = self::contentTypes['listFoldersFoldersGet_0'][0])
    {
        $returnType = '\Camb.ai\Model\Folder[]';
        $request = $this->listFoldersFoldersGet_0Request($limit, $search_query, $run_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listFoldersFoldersGet_0'
     *
     * @param  int|null $limit (optional)
     * @param  string|null $search_query (optional)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listFoldersFoldersGet_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listFoldersFoldersGet_0Request($limit = null, $search_query = null, $run_id = null, string $contentType = self::contentTypes['listFoldersFoldersGet_0'][0])
    {

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling FoldersApi.listFoldersFoldersGet_0, must be smaller than or equal to 100.');
        }
        
        if ($search_query !== null && strlen($search_query) > 255) {
            throw new \InvalidArgumentException('invalid length for "$search_query" when calling FoldersApi.listFoldersFoldersGet_0, must be smaller than or equal to 255.');
        }
        if ($search_query !== null && strlen($search_query) < 2) {
            throw new \InvalidArgumentException('invalid length for "$search_query" when calling FoldersApi.listFoldersFoldersGet_0, must be bigger than or equal to 2.');
        }
        


        $resourcePath = '/folders';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search_query,
            'search_query', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
