<?php
/**
 * StoryApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Camb\Ai\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Camb\Ai\ApiException;
use Camb\Ai\Configuration;
use Camb\Ai\FormDataProcessor;
use Camb\Ai\HeaderSelector;
use Camb\Ai\ObjectSerializer;

/**
 * StoryApi Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StoryApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createStoryStoryPost' => [
            'multipart/form-data',
        ],
        'getStoriesRunsResultsStoriesResultsPost' => [
            'application/json',
        ],
        'getStoryRunInfoStoryResultRunIdGet' => [
            'application/json',
        ],
        'getStoryStatusStoryTaskIdGet' => [
            'application/json',
        ],
        'setupStoryStorySetupPost' => [
            'multipart/form-data',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createStoryStoryPost
     *
     * Create Story
     *
     * @param  \SplFileObject $file Text File or Word Document (Docx) for Creating a Story. (required)
     * @param  \Camb.ai\Model\Languages $source_language source_language (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string|null $title title (optional)
     * @param  string|null $description description (optional)
     * @param  int|null $narrator_voice_id narrator_voice_id (optional)
     * @param  int|null $folder_id folder_id (optional)
     * @param  int[]|null $chosen_dictionaries chosen_dictionaries (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStoryStoryPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Camb.ai\Model\ResponseCreateStoryStoryPost|\Camb.ai\Model\HTTPValidationError
     */
    public function createStoryStoryPost($file, $source_language, $run_id = null, $title = null, $description = null, $narrator_voice_id = null, $folder_id = null, $chosen_dictionaries = null, string $contentType = self::contentTypes['createStoryStoryPost'][0])
    {
        list($response) = $this->createStoryStoryPostWithHttpInfo($file, $source_language, $run_id, $title, $description, $narrator_voice_id, $folder_id, $chosen_dictionaries, $contentType);
        return $response;
    }

    /**
     * Operation createStoryStoryPostWithHttpInfo
     *
     * Create Story
     *
     * @param  \SplFileObject $file Text File or Word Document (Docx) for Creating a Story. (required)
     * @param  \Camb.ai\Model\Languages $source_language (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $title (optional)
     * @param  string|null $description (optional)
     * @param  int|null $narrator_voice_id (optional)
     * @param  int|null $folder_id (optional)
     * @param  int[]|null $chosen_dictionaries (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStoryStoryPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Camb.ai\Model\ResponseCreateStoryStoryPost|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createStoryStoryPostWithHttpInfo($file, $source_language, $run_id = null, $title = null, $description = null, $narrator_voice_id = null, $folder_id = null, $chosen_dictionaries = null, string $contentType = self::contentTypes['createStoryStoryPost'][0])
    {
        $request = $this->createStoryStoryPostRequest($file, $source_language, $run_id, $title, $description, $narrator_voice_id, $folder_id, $chosen_dictionaries, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\ResponseCreateStoryStoryPost',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Camb.ai\Model\ResponseCreateStoryStoryPost',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\ResponseCreateStoryStoryPost',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createStoryStoryPostAsync
     *
     * Create Story
     *
     * @param  \SplFileObject $file Text File or Word Document (Docx) for Creating a Story. (required)
     * @param  \Camb.ai\Model\Languages $source_language (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $title (optional)
     * @param  string|null $description (optional)
     * @param  int|null $narrator_voice_id (optional)
     * @param  int|null $folder_id (optional)
     * @param  int[]|null $chosen_dictionaries (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStoryStoryPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createStoryStoryPostAsync($file, $source_language, $run_id = null, $title = null, $description = null, $narrator_voice_id = null, $folder_id = null, $chosen_dictionaries = null, string $contentType = self::contentTypes['createStoryStoryPost'][0])
    {
        return $this->createStoryStoryPostAsyncWithHttpInfo($file, $source_language, $run_id, $title, $description, $narrator_voice_id, $folder_id, $chosen_dictionaries, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createStoryStoryPostAsyncWithHttpInfo
     *
     * Create Story
     *
     * @param  \SplFileObject $file Text File or Word Document (Docx) for Creating a Story. (required)
     * @param  \Camb.ai\Model\Languages $source_language (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $title (optional)
     * @param  string|null $description (optional)
     * @param  int|null $narrator_voice_id (optional)
     * @param  int|null $folder_id (optional)
     * @param  int[]|null $chosen_dictionaries (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStoryStoryPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createStoryStoryPostAsyncWithHttpInfo($file, $source_language, $run_id = null, $title = null, $description = null, $narrator_voice_id = null, $folder_id = null, $chosen_dictionaries = null, string $contentType = self::contentTypes['createStoryStoryPost'][0])
    {
        $returnType = '\Camb.ai\Model\ResponseCreateStoryStoryPost';
        $request = $this->createStoryStoryPostRequest($file, $source_language, $run_id, $title, $description, $narrator_voice_id, $folder_id, $chosen_dictionaries, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createStoryStoryPost'
     *
     * @param  \SplFileObject $file Text File or Word Document (Docx) for Creating a Story. (required)
     * @param  \Camb.ai\Model\Languages $source_language (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $title (optional)
     * @param  string|null $description (optional)
     * @param  int|null $narrator_voice_id (optional)
     * @param  int|null $folder_id (optional)
     * @param  int[]|null $chosen_dictionaries (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStoryStoryPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createStoryStoryPostRequest($file, $source_language, $run_id = null, $title = null, $description = null, $narrator_voice_id = null, $folder_id = null, $chosen_dictionaries = null, string $contentType = self::contentTypes['createStoryStoryPost'][0])
    {

        // verify the required parameter 'file' is set
        if ($file === null || (is_array($file) && count($file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $file when calling createStoryStoryPost'
            );
        }

        // verify the required parameter 'source_language' is set
        if ($source_language === null || (is_array($source_language) && count($source_language) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $source_language when calling createStoryStoryPost'
            );
        }


        if ($title !== null && strlen($title) > 255) {
            throw new \InvalidArgumentException('invalid length for "$title" when calling StoryApi.createStoryStoryPost, must be smaller than or equal to 255.');
        }
        if ($title !== null && strlen($title) < 3) {
            throw new \InvalidArgumentException('invalid length for "$title" when calling StoryApi.createStoryStoryPost, must be bigger than or equal to 3.');
        }
        
        if ($description !== null && strlen($description) > 5000) {
            throw new \InvalidArgumentException('invalid length for "$description" when calling StoryApi.createStoryStoryPost, must be smaller than or equal to 5000.');
        }
        if ($description !== null && strlen($description) < 3) {
            throw new \InvalidArgumentException('invalid length for "$description" when calling StoryApi.createStoryStoryPost, must be bigger than or equal to 3.');
        }
        




        $resourcePath = '/story';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);



        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'file' => $file,
            'source_language' => $source_language,
            'title' => $title,
            'description' => $description,
            'narrator_voice_id' => $narrator_voice_id,
            'folder_id' => $folder_id,
            'chosen_dictionaries' => $chosen_dictionaries,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getStoriesRunsResultsStoriesResultsPost
     *
     * Get Stories Runs Results
     *
     * @param  \Camb.ai\Model\RunIDsRequestPayload $run_ids_request_payload run_ids_request_payload (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string|null $traceparent traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoriesRunsResultsStoriesResultsPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array<string,array<string,mixed>>|\Camb.ai\Model\HTTPValidationError
     */
    public function getStoriesRunsResultsStoriesResultsPost($run_ids_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getStoriesRunsResultsStoriesResultsPost'][0])
    {
        list($response) = $this->getStoriesRunsResultsStoriesResultsPostWithHttpInfo($run_ids_request_payload, $run_id, $traceparent, $contentType);
        return $response;
    }

    /**
     * Operation getStoriesRunsResultsStoriesResultsPostWithHttpInfo
     *
     * Get Stories Runs Results
     *
     * @param  \Camb.ai\Model\RunIDsRequestPayload $run_ids_request_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoriesRunsResultsStoriesResultsPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of array<string,array<string,mixed>>|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getStoriesRunsResultsStoriesResultsPostWithHttpInfo($run_ids_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getStoriesRunsResultsStoriesResultsPost'][0])
    {
        $request = $this->getStoriesRunsResultsStoriesResultsPostRequest($run_ids_request_payload, $run_id, $traceparent, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'array<string,array<string,mixed>>',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'array<string,array<string,mixed>>',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,array<string,mixed>>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getStoriesRunsResultsStoriesResultsPostAsync
     *
     * Get Stories Runs Results
     *
     * @param  \Camb.ai\Model\RunIDsRequestPayload $run_ids_request_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoriesRunsResultsStoriesResultsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStoriesRunsResultsStoriesResultsPostAsync($run_ids_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getStoriesRunsResultsStoriesResultsPost'][0])
    {
        return $this->getStoriesRunsResultsStoriesResultsPostAsyncWithHttpInfo($run_ids_request_payload, $run_id, $traceparent, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getStoriesRunsResultsStoriesResultsPostAsyncWithHttpInfo
     *
     * Get Stories Runs Results
     *
     * @param  \Camb.ai\Model\RunIDsRequestPayload $run_ids_request_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoriesRunsResultsStoriesResultsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStoriesRunsResultsStoriesResultsPostAsyncWithHttpInfo($run_ids_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getStoriesRunsResultsStoriesResultsPost'][0])
    {
        $returnType = 'array<string,array<string,mixed>>';
        $request = $this->getStoriesRunsResultsStoriesResultsPostRequest($run_ids_request_payload, $run_id, $traceparent, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getStoriesRunsResultsStoriesResultsPost'
     *
     * @param  \Camb.ai\Model\RunIDsRequestPayload $run_ids_request_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoriesRunsResultsStoriesResultsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getStoriesRunsResultsStoriesResultsPostRequest($run_ids_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['getStoriesRunsResultsStoriesResultsPost'][0])
    {

        // verify the required parameter 'run_ids_request_payload' is set
        if ($run_ids_request_payload === null || (is_array($run_ids_request_payload) && count($run_ids_request_payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $run_ids_request_payload when calling getStoriesRunsResultsStoriesResultsPost'
            );
        }




        $resourcePath = '/stories-results';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($traceparent !== null) {
            $headerParams['traceparent'] = ObjectSerializer::toHeaderValue($traceparent);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($run_ids_request_payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($run_ids_request_payload));
            } else {
                $httpBody = $run_ids_request_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getStoryRunInfoStoryResultRunIdGet
     *
     * Get Story Run Info
     *
     * @param  int|null $run_id run_id (required)
     * @param  bool|null $include_transcript Whether to include the transcription in the response for fetching the result of a Stories run. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoryRunInfoStoryResultRunIdGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array<string,mixed>|\Camb.ai\Model\HTTPValidationError
     */
    public function getStoryRunInfoStoryResultRunIdGet($run_id, $include_transcript = null, string $contentType = self::contentTypes['getStoryRunInfoStoryResultRunIdGet'][0])
    {
        list($response) = $this->getStoryRunInfoStoryResultRunIdGetWithHttpInfo($run_id, $include_transcript, $contentType);
        return $response;
    }

    /**
     * Operation getStoryRunInfoStoryResultRunIdGetWithHttpInfo
     *
     * Get Story Run Info
     *
     * @param  int|null $run_id (required)
     * @param  bool|null $include_transcript Whether to include the transcription in the response for fetching the result of a Stories run. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoryRunInfoStoryResultRunIdGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of array<string,mixed>|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getStoryRunInfoStoryResultRunIdGetWithHttpInfo($run_id, $include_transcript = null, string $contentType = self::contentTypes['getStoryRunInfoStoryResultRunIdGet'][0])
    {
        $request = $this->getStoryRunInfoStoryResultRunIdGetRequest($run_id, $include_transcript, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'array<string,mixed>',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'array<string,mixed>',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,mixed>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getStoryRunInfoStoryResultRunIdGetAsync
     *
     * Get Story Run Info
     *
     * @param  int|null $run_id (required)
     * @param  bool|null $include_transcript Whether to include the transcription in the response for fetching the result of a Stories run. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoryRunInfoStoryResultRunIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStoryRunInfoStoryResultRunIdGetAsync($run_id, $include_transcript = null, string $contentType = self::contentTypes['getStoryRunInfoStoryResultRunIdGet'][0])
    {
        return $this->getStoryRunInfoStoryResultRunIdGetAsyncWithHttpInfo($run_id, $include_transcript, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getStoryRunInfoStoryResultRunIdGetAsyncWithHttpInfo
     *
     * Get Story Run Info
     *
     * @param  int|null $run_id (required)
     * @param  bool|null $include_transcript Whether to include the transcription in the response for fetching the result of a Stories run. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoryRunInfoStoryResultRunIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStoryRunInfoStoryResultRunIdGetAsyncWithHttpInfo($run_id, $include_transcript = null, string $contentType = self::contentTypes['getStoryRunInfoStoryResultRunIdGet'][0])
    {
        $returnType = 'array<string,mixed>';
        $request = $this->getStoryRunInfoStoryResultRunIdGetRequest($run_id, $include_transcript, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getStoryRunInfoStoryResultRunIdGet'
     *
     * @param  int|null $run_id (required)
     * @param  bool|null $include_transcript Whether to include the transcription in the response for fetching the result of a Stories run. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoryRunInfoStoryResultRunIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getStoryRunInfoStoryResultRunIdGetRequest($run_id, $include_transcript = null, string $contentType = self::contentTypes['getStoryRunInfoStoryResultRunIdGet'][0])
    {

        // verify the required parameter 'run_id' is set
        if ($run_id === null || (is_array($run_id) && count($run_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $run_id when calling getStoryRunInfoStoryResultRunIdGet'
            );
        }



        $resourcePath = '/story-result/{run_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_transcript,
            'include_transcript', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($run_id !== null) {
            $resourcePath = str_replace(
                '{' . 'run_id' . '}',
                ObjectSerializer::toPathValue($run_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getStoryStatusStoryTaskIdGet
     *
     * Get Story Status
     *
     * @param  string $task_id task_id (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoryStatusStoryTaskIdGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Camb.ai\Model\OrchestratorPipelineResult|\Camb.ai\Model\HTTPValidationError
     */
    public function getStoryStatusStoryTaskIdGet($task_id, $run_id = null, string $contentType = self::contentTypes['getStoryStatusStoryTaskIdGet'][0])
    {
        list($response) = $this->getStoryStatusStoryTaskIdGetWithHttpInfo($task_id, $run_id, $contentType);
        return $response;
    }

    /**
     * Operation getStoryStatusStoryTaskIdGetWithHttpInfo
     *
     * Get Story Status
     *
     * @param  string $task_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoryStatusStoryTaskIdGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Camb.ai\Model\OrchestratorPipelineResult|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getStoryStatusStoryTaskIdGetWithHttpInfo($task_id, $run_id = null, string $contentType = self::contentTypes['getStoryStatusStoryTaskIdGet'][0])
    {
        $request = $this->getStoryStatusStoryTaskIdGetRequest($task_id, $run_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\OrchestratorPipelineResult',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Camb.ai\Model\OrchestratorPipelineResult',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\OrchestratorPipelineResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getStoryStatusStoryTaskIdGetAsync
     *
     * Get Story Status
     *
     * @param  string $task_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoryStatusStoryTaskIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStoryStatusStoryTaskIdGetAsync($task_id, $run_id = null, string $contentType = self::contentTypes['getStoryStatusStoryTaskIdGet'][0])
    {
        return $this->getStoryStatusStoryTaskIdGetAsyncWithHttpInfo($task_id, $run_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getStoryStatusStoryTaskIdGetAsyncWithHttpInfo
     *
     * Get Story Status
     *
     * @param  string $task_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoryStatusStoryTaskIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStoryStatusStoryTaskIdGetAsyncWithHttpInfo($task_id, $run_id = null, string $contentType = self::contentTypes['getStoryStatusStoryTaskIdGet'][0])
    {
        $returnType = '\Camb.ai\Model\OrchestratorPipelineResult';
        $request = $this->getStoryStatusStoryTaskIdGetRequest($task_id, $run_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getStoryStatusStoryTaskIdGet'
     *
     * @param  string $task_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStoryStatusStoryTaskIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getStoryStatusStoryTaskIdGetRequest($task_id, $run_id = null, string $contentType = self::contentTypes['getStoryStatusStoryTaskIdGet'][0])
    {

        // verify the required parameter 'task_id' is set
        if ($task_id === null || (is_array($task_id) && count($task_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $task_id when calling getStoryStatusStoryTaskIdGet'
            );
        }



        $resourcePath = '/story/{task_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($task_id !== null) {
            $resourcePath = str_replace(
                '{' . 'task_id' . '}',
                ObjectSerializer::toPathValue($task_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation setupStoryStorySetupPost
     *
     * Setup Story
     *
     * @param  \SplFileObject $file Text File or Word Document (Docx) for Creating a Story. (required)
     * @param  \Camb.ai\Model\Languages $source_language source_language (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string|null $title title (optional)
     * @param  string|null $description description (optional)
     * @param  int|null $narrator_voice_id narrator_voice_id (optional)
     * @param  int|null $folder_id folder_id (optional)
     * @param  int[]|null $chosen_dictionaries chosen_dictionaries (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setupStoryStorySetupPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Camb.ai\Model\ResponseSetupStoryStorySetupPost|\Camb.ai\Model\HTTPValidationError
     */
    public function setupStoryStorySetupPost($file, $source_language, $run_id = null, $title = null, $description = null, $narrator_voice_id = null, $folder_id = null, $chosen_dictionaries = null, string $contentType = self::contentTypes['setupStoryStorySetupPost'][0])
    {
        list($response) = $this->setupStoryStorySetupPostWithHttpInfo($file, $source_language, $run_id, $title, $description, $narrator_voice_id, $folder_id, $chosen_dictionaries, $contentType);
        return $response;
    }

    /**
     * Operation setupStoryStorySetupPostWithHttpInfo
     *
     * Setup Story
     *
     * @param  \SplFileObject $file Text File or Word Document (Docx) for Creating a Story. (required)
     * @param  \Camb.ai\Model\Languages $source_language (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $title (optional)
     * @param  string|null $description (optional)
     * @param  int|null $narrator_voice_id (optional)
     * @param  int|null $folder_id (optional)
     * @param  int[]|null $chosen_dictionaries (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setupStoryStorySetupPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Camb.ai\Model\ResponseSetupStoryStorySetupPost|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function setupStoryStorySetupPostWithHttpInfo($file, $source_language, $run_id = null, $title = null, $description = null, $narrator_voice_id = null, $folder_id = null, $chosen_dictionaries = null, string $contentType = self::contentTypes['setupStoryStorySetupPost'][0])
    {
        $request = $this->setupStoryStorySetupPostRequest($file, $source_language, $run_id, $title, $description, $narrator_voice_id, $folder_id, $chosen_dictionaries, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\ResponseSetupStoryStorySetupPost',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Camb.ai\Model\ResponseSetupStoryStorySetupPost',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\ResponseSetupStoryStorySetupPost',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation setupStoryStorySetupPostAsync
     *
     * Setup Story
     *
     * @param  \SplFileObject $file Text File or Word Document (Docx) for Creating a Story. (required)
     * @param  \Camb.ai\Model\Languages $source_language (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $title (optional)
     * @param  string|null $description (optional)
     * @param  int|null $narrator_voice_id (optional)
     * @param  int|null $folder_id (optional)
     * @param  int[]|null $chosen_dictionaries (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setupStoryStorySetupPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setupStoryStorySetupPostAsync($file, $source_language, $run_id = null, $title = null, $description = null, $narrator_voice_id = null, $folder_id = null, $chosen_dictionaries = null, string $contentType = self::contentTypes['setupStoryStorySetupPost'][0])
    {
        return $this->setupStoryStorySetupPostAsyncWithHttpInfo($file, $source_language, $run_id, $title, $description, $narrator_voice_id, $folder_id, $chosen_dictionaries, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation setupStoryStorySetupPostAsyncWithHttpInfo
     *
     * Setup Story
     *
     * @param  \SplFileObject $file Text File or Word Document (Docx) for Creating a Story. (required)
     * @param  \Camb.ai\Model\Languages $source_language (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $title (optional)
     * @param  string|null $description (optional)
     * @param  int|null $narrator_voice_id (optional)
     * @param  int|null $folder_id (optional)
     * @param  int[]|null $chosen_dictionaries (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setupStoryStorySetupPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function setupStoryStorySetupPostAsyncWithHttpInfo($file, $source_language, $run_id = null, $title = null, $description = null, $narrator_voice_id = null, $folder_id = null, $chosen_dictionaries = null, string $contentType = self::contentTypes['setupStoryStorySetupPost'][0])
    {
        $returnType = '\Camb.ai\Model\ResponseSetupStoryStorySetupPost';
        $request = $this->setupStoryStorySetupPostRequest($file, $source_language, $run_id, $title, $description, $narrator_voice_id, $folder_id, $chosen_dictionaries, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'setupStoryStorySetupPost'
     *
     * @param  \SplFileObject $file Text File or Word Document (Docx) for Creating a Story. (required)
     * @param  \Camb.ai\Model\Languages $source_language (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $title (optional)
     * @param  string|null $description (optional)
     * @param  int|null $narrator_voice_id (optional)
     * @param  int|null $folder_id (optional)
     * @param  int[]|null $chosen_dictionaries (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['setupStoryStorySetupPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function setupStoryStorySetupPostRequest($file, $source_language, $run_id = null, $title = null, $description = null, $narrator_voice_id = null, $folder_id = null, $chosen_dictionaries = null, string $contentType = self::contentTypes['setupStoryStorySetupPost'][0])
    {

        // verify the required parameter 'file' is set
        if ($file === null || (is_array($file) && count($file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $file when calling setupStoryStorySetupPost'
            );
        }

        // verify the required parameter 'source_language' is set
        if ($source_language === null || (is_array($source_language) && count($source_language) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $source_language when calling setupStoryStorySetupPost'
            );
        }


        if ($title !== null && strlen($title) > 255) {
            throw new \InvalidArgumentException('invalid length for "$title" when calling StoryApi.setupStoryStorySetupPost, must be smaller than or equal to 255.');
        }
        if ($title !== null && strlen($title) < 3) {
            throw new \InvalidArgumentException('invalid length for "$title" when calling StoryApi.setupStoryStorySetupPost, must be bigger than or equal to 3.');
        }
        
        if ($description !== null && strlen($description) > 5000) {
            throw new \InvalidArgumentException('invalid length for "$description" when calling StoryApi.setupStoryStorySetupPost, must be smaller than or equal to 5000.');
        }
        if ($description !== null && strlen($description) < 3) {
            throw new \InvalidArgumentException('invalid length for "$description" when calling StoryApi.setupStoryStorySetupPost, must be bigger than or equal to 3.');
        }
        




        $resourcePath = '/story-setup';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);



        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'file' => $file,
            'source_language' => $source_language,
            'title' => $title,
            'description' => $description,
            'narrator_voice_id' => $narrator_voice_id,
            'folder_id' => $folder_id,
            'chosen_dictionaries' => $chosen_dictionaries,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
