<?php
/**
 * TranslatedTTSApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Camb.ai\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Camb.ai\ApiException;
use Camb.ai\Configuration;
use Camb.ai\FormDataProcessor;
use Camb.ai\HeaderSelector;
use Camb.ai\ObjectSerializer;

/**
 * TranslatedTTSApi Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TranslatedTTSApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createTranslatedTtsTranslatedTtsPost' => [
            'application/json',
        ],
        'getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createTranslatedTtsTranslatedTtsPost
     *
     * Create Translated Tts
     *
     * @param  \Camb.ai\Model\CreateTranslatedTTSRequestPayload $create_translated_tts_request_payload create_translated_tts_request_payload (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string|null $traceparent traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createTranslatedTtsTranslatedTtsPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Camb.ai\Model\CreateTranslatedTTSOut|\Camb.ai\Model\HTTPValidationError
     */
    public function createTranslatedTtsTranslatedTtsPost($create_translated_tts_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['createTranslatedTtsTranslatedTtsPost'][0])
    {
        list($response) = $this->createTranslatedTtsTranslatedTtsPostWithHttpInfo($create_translated_tts_request_payload, $run_id, $traceparent, $contentType);
        return $response;
    }

    /**
     * Operation createTranslatedTtsTranslatedTtsPostWithHttpInfo
     *
     * Create Translated Tts
     *
     * @param  \Camb.ai\Model\CreateTranslatedTTSRequestPayload $create_translated_tts_request_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createTranslatedTtsTranslatedTtsPost'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Camb.ai\Model\CreateTranslatedTTSOut|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createTranslatedTtsTranslatedTtsPostWithHttpInfo($create_translated_tts_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['createTranslatedTtsTranslatedTtsPost'][0])
    {
        $request = $this->createTranslatedTtsTranslatedTtsPostRequest($create_translated_tts_request_payload, $run_id, $traceparent, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\CreateTranslatedTTSOut',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Camb.ai\Model\CreateTranslatedTTSOut',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\CreateTranslatedTTSOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createTranslatedTtsTranslatedTtsPostAsync
     *
     * Create Translated Tts
     *
     * @param  \Camb.ai\Model\CreateTranslatedTTSRequestPayload $create_translated_tts_request_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createTranslatedTtsTranslatedTtsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createTranslatedTtsTranslatedTtsPostAsync($create_translated_tts_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['createTranslatedTtsTranslatedTtsPost'][0])
    {
        return $this->createTranslatedTtsTranslatedTtsPostAsyncWithHttpInfo($create_translated_tts_request_payload, $run_id, $traceparent, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createTranslatedTtsTranslatedTtsPostAsyncWithHttpInfo
     *
     * Create Translated Tts
     *
     * @param  \Camb.ai\Model\CreateTranslatedTTSRequestPayload $create_translated_tts_request_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createTranslatedTtsTranslatedTtsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createTranslatedTtsTranslatedTtsPostAsyncWithHttpInfo($create_translated_tts_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['createTranslatedTtsTranslatedTtsPost'][0])
    {
        $returnType = '\Camb.ai\Model\CreateTranslatedTTSOut';
        $request = $this->createTranslatedTtsTranslatedTtsPostRequest($create_translated_tts_request_payload, $run_id, $traceparent, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createTranslatedTtsTranslatedTtsPost'
     *
     * @param  \Camb.ai\Model\CreateTranslatedTTSRequestPayload $create_translated_tts_request_payload (required)
     * @param  int|null $run_id (optional)
     * @param  string|null $traceparent (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createTranslatedTtsTranslatedTtsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createTranslatedTtsTranslatedTtsPostRequest($create_translated_tts_request_payload, $run_id = null, $traceparent = null, string $contentType = self::contentTypes['createTranslatedTtsTranslatedTtsPost'][0])
    {

        // verify the required parameter 'create_translated_tts_request_payload' is set
        if ($create_translated_tts_request_payload === null || (is_array($create_translated_tts_request_payload) && count($create_translated_tts_request_payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_translated_tts_request_payload when calling createTranslatedTtsTranslatedTtsPost'
            );
        }




        $resourcePath = '/translated-tts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($traceparent !== null) {
            $headerParams['traceparent'] = ObjectSerializer::toHeaderValue($traceparent);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_translated_tts_request_payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_translated_tts_request_payload));
            } else {
                $httpBody = $create_translated_tts_request_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet
     *
     * Get Translated Tts Task Status
     *
     * @param  string $task_id task_id (required)
     * @param  int|null $run_id run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Camb.ai\Model\OrchestratorPipelineResult|\Camb.ai\Model\HTTPValidationError
     */
    public function getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet($task_id, $run_id = null, string $contentType = self::contentTypes['getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet'][0])
    {
        list($response) = $this->getTranslatedTtsTaskStatusTranslatedTtsTaskIdGetWithHttpInfo($task_id, $run_id, $contentType);
        return $response;
    }

    /**
     * Operation getTranslatedTtsTaskStatusTranslatedTtsTaskIdGetWithHttpInfo
     *
     * Get Translated Tts Task Status
     *
     * @param  string $task_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet'] to see the possible values for this operation
     *
     * @throws \Camb.ai\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Camb.ai\Model\OrchestratorPipelineResult|\Camb.ai\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTranslatedTtsTaskStatusTranslatedTtsTaskIdGetWithHttpInfo($task_id, $run_id = null, string $contentType = self::contentTypes['getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet'][0])
    {
        $request = $this->getTranslatedTtsTaskStatusTranslatedTtsTaskIdGetRequest($task_id, $run_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\OrchestratorPipelineResult',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Camb.ai\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Camb.ai\Model\OrchestratorPipelineResult',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\OrchestratorPipelineResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Camb.ai\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getTranslatedTtsTaskStatusTranslatedTtsTaskIdGetAsync
     *
     * Get Translated Tts Task Status
     *
     * @param  string $task_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTranslatedTtsTaskStatusTranslatedTtsTaskIdGetAsync($task_id, $run_id = null, string $contentType = self::contentTypes['getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet'][0])
    {
        return $this->getTranslatedTtsTaskStatusTranslatedTtsTaskIdGetAsyncWithHttpInfo($task_id, $run_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTranslatedTtsTaskStatusTranslatedTtsTaskIdGetAsyncWithHttpInfo
     *
     * Get Translated Tts Task Status
     *
     * @param  string $task_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTranslatedTtsTaskStatusTranslatedTtsTaskIdGetAsyncWithHttpInfo($task_id, $run_id = null, string $contentType = self::contentTypes['getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet'][0])
    {
        $returnType = '\Camb.ai\Model\OrchestratorPipelineResult';
        $request = $this->getTranslatedTtsTaskStatusTranslatedTtsTaskIdGetRequest($task_id, $run_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet'
     *
     * @param  string $task_id (required)
     * @param  int|null $run_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getTranslatedTtsTaskStatusTranslatedTtsTaskIdGetRequest($task_id, $run_id = null, string $contentType = self::contentTypes['getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet'][0])
    {

        // verify the required parameter 'task_id' is set
        if ($task_id === null || (is_array($task_id) && count($task_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $task_id when calling getTranslatedTtsTaskStatusTranslatedTtsTaskIdGet'
            );
        }



        $resourcePath = '/translated-tts/{task_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $run_id,
            'run_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($task_id !== null) {
            $resourcePath = str_replace(
                '{' . 'task_id' . '}',
                ObjectSerializer::toPathValue($task_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
