<?php
/**
 * CreateTextToVoiceRequestPayload
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Camb.ai\Model;

use \ArrayAccess;
use \Camb.ai\ObjectSerializer;

/**
 * CreateTextToVoiceRequestPayload Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateTextToVoiceRequestPayload implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateTextToVoiceRequestPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'project_name' => 'string',
        'project_description' => 'string',
        'folder_id' => 'int',
        'text' => 'string',
        'voice_description' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'project_name' => null,
        'project_description' => null,
        'folder_id' => null,
        'text' => null,
        'voice_description' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'project_name' => true,
        'project_description' => true,
        'folder_id' => true,
        'text' => false,
        'voice_description' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'project_name' => 'project_name',
        'project_description' => 'project_description',
        'folder_id' => 'folder_id',
        'text' => 'text',
        'voice_description' => 'voice_description'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'project_name' => 'setProjectName',
        'project_description' => 'setProjectDescription',
        'folder_id' => 'setFolderId',
        'text' => 'setText',
        'voice_description' => 'setVoiceDescription'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'project_name' => 'getProjectName',
        'project_description' => 'getProjectDescription',
        'folder_id' => 'getFolderId',
        'text' => 'getText',
        'voice_description' => 'getVoiceDescription'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('project_name', $data ?? [], null);
        $this->setIfExists('project_description', $data ?? [], null);
        $this->setIfExists('folder_id', $data ?? [], null);
        $this->setIfExists('text', $data ?? [], null);
        $this->setIfExists('voice_description', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['project_name']) && (mb_strlen($this->container['project_name']) > 255)) {
            $invalidProperties[] = "invalid value for 'project_name', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['project_name']) && (mb_strlen($this->container['project_name']) < 3)) {
            $invalidProperties[] = "invalid value for 'project_name', the character length must be bigger than or equal to 3.";
        }

        if (!is_null($this->container['project_description']) && (mb_strlen($this->container['project_description']) > 5000)) {
            $invalidProperties[] = "invalid value for 'project_description', the character length must be smaller than or equal to 5000.";
        }

        if (!is_null($this->container['project_description']) && (mb_strlen($this->container['project_description']) < 3)) {
            $invalidProperties[] = "invalid value for 'project_description', the character length must be bigger than or equal to 3.";
        }

        if ($this->container['text'] === null) {
            $invalidProperties[] = "'text' can't be null";
        }
        if ((mb_strlen($this->container['text']) > 1000)) {
            $invalidProperties[] = "invalid value for 'text', the character length must be smaller than or equal to 1000.";
        }

        if ((mb_strlen($this->container['text']) < 100)) {
            $invalidProperties[] = "invalid value for 'text', the character length must be bigger than or equal to 100.";
        }

        if ($this->container['voice_description'] === null) {
            $invalidProperties[] = "'voice_description' can't be null";
        }
        if ((mb_strlen($this->container['voice_description']) > 1000)) {
            $invalidProperties[] = "invalid value for 'voice_description', the character length must be smaller than or equal to 1000.";
        }

        if ((mb_strlen($this->container['voice_description']) < 20)) {
            $invalidProperties[] = "invalid value for 'voice_description', the character length must be bigger than or equal to 20.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets project_name
     *
     * @return string|null
     */
    public function getProjectName()
    {
        return $this->container['project_name'];
    }

    /**
     * Sets project_name
     *
     * @param string|null $project_name project_name
     *
     * @return self
     */
    public function setProjectName($project_name)
    {
        if (is_null($project_name)) {
            array_push($this->openAPINullablesSetToNull, 'project_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('project_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($project_name) && (mb_strlen($project_name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $project_name when calling CreateTextToVoiceRequestPayload., must be smaller than or equal to 255.');
        }
        if (!is_null($project_name) && (mb_strlen($project_name) < 3)) {
            throw new \InvalidArgumentException('invalid length for $project_name when calling CreateTextToVoiceRequestPayload., must be bigger than or equal to 3.');
        }

        $this->container['project_name'] = $project_name;

        return $this;
    }

    /**
     * Gets project_description
     *
     * @return string|null
     */
    public function getProjectDescription()
    {
        return $this->container['project_description'];
    }

    /**
     * Sets project_description
     *
     * @param string|null $project_description project_description
     *
     * @return self
     */
    public function setProjectDescription($project_description)
    {
        if (is_null($project_description)) {
            array_push($this->openAPINullablesSetToNull, 'project_description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('project_description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($project_description) && (mb_strlen($project_description) > 5000)) {
            throw new \InvalidArgumentException('invalid length for $project_description when calling CreateTextToVoiceRequestPayload., must be smaller than or equal to 5000.');
        }
        if (!is_null($project_description) && (mb_strlen($project_description) < 3)) {
            throw new \InvalidArgumentException('invalid length for $project_description when calling CreateTextToVoiceRequestPayload., must be bigger than or equal to 3.');
        }

        $this->container['project_description'] = $project_description;

        return $this;
    }

    /**
     * Gets folder_id
     *
     * @return int|null
     */
    public function getFolderId()
    {
        return $this->container['folder_id'];
    }

    /**
     * Sets folder_id
     *
     * @param int|null $folder_id folder_id
     *
     * @return self
     */
    public function setFolderId($folder_id)
    {
        if (is_null($folder_id)) {
            array_push($this->openAPINullablesSetToNull, 'folder_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('folder_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['folder_id'] = $folder_id;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string $text The text to be converted to voice
     *
     * @return self
     */
    public function setText($text)
    {
        if (is_null($text)) {
            throw new \InvalidArgumentException('non-nullable text cannot be null');
        }
        if ((mb_strlen($text) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $text when calling CreateTextToVoiceRequestPayload., must be smaller than or equal to 1000.');
        }
        if ((mb_strlen($text) < 100)) {
            throw new \InvalidArgumentException('invalid length for $text when calling CreateTextToVoiceRequestPayload., must be bigger than or equal to 100.');
        }

        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets voice_description
     *
     * @return string
     */
    public function getVoiceDescription()
    {
        return $this->container['voice_description'];
    }

    /**
     * Sets voice_description
     *
     * @param string $voice_description Description to use for the created voice
     *
     * @return self
     */
    public function setVoiceDescription($voice_description)
    {
        if (is_null($voice_description)) {
            throw new \InvalidArgumentException('non-nullable voice_description cannot be null');
        }
        if ((mb_strlen($voice_description) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $voice_description when calling CreateTextToVoiceRequestPayload., must be smaller than or equal to 1000.');
        }
        if ((mb_strlen($voice_description) < 20)) {
            throw new \InvalidArgumentException('invalid length for $voice_description when calling CreateTextToVoiceRequestPayload., must be bigger than or equal to 20.');
        }

        $this->container['voice_description'] = $voice_description;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


