<?php
/**
 * CreateStreamRequestPayload
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Camb\Ai\Model;

use \ArrayAccess;
use \Camb\Ai\ObjectSerializer;

/**
 * CreateStreamRequestPayload Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateStreamRequestPayload implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateStreamRequestPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'description' => 'string',
        'initial_delay' => 'int',
        'timeout_in_mins' => 'int',
        'voices' => 'int[]',
        'dictionaries' => 'int[]',
        'config' => '\Camb.ai\Model\ConfigStream',
        'source_stream' => '\Camb.ai\Model\SourceStream',
        'target_streams' => '\Camb.ai\Model\TargetStream[]',
        'start_time' => '\DateTime',
        'end_time' => '\DateTime',
        'timezone' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'description' => null,
        'initial_delay' => null,
        'timeout_in_mins' => null,
        'voices' => null,
        'dictionaries' => null,
        'config' => null,
        'source_stream' => null,
        'target_streams' => null,
        'start_time' => 'date-time',
        'end_time' => 'date-time',
        'timezone' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => true,
        'description' => true,
        'initial_delay' => false,
        'timeout_in_mins' => true,
        'voices' => false,
        'dictionaries' => false,
        'config' => false,
        'source_stream' => false,
        'target_streams' => false,
        'start_time' => true,
        'end_time' => true,
        'timezone' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'description' => 'description',
        'initial_delay' => 'initial_delay',
        'timeout_in_mins' => 'timeout_in_mins',
        'voices' => 'voices',
        'dictionaries' => 'dictionaries',
        'config' => 'config',
        'source_stream' => 'source_stream',
        'target_streams' => 'target_streams',
        'start_time' => 'start_time',
        'end_time' => 'end_time',
        'timezone' => 'timezone'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'description' => 'setDescription',
        'initial_delay' => 'setInitialDelay',
        'timeout_in_mins' => 'setTimeoutInMins',
        'voices' => 'setVoices',
        'dictionaries' => 'setDictionaries',
        'config' => 'setConfig',
        'source_stream' => 'setSourceStream',
        'target_streams' => 'setTargetStreams',
        'start_time' => 'setStartTime',
        'end_time' => 'setEndTime',
        'timezone' => 'setTimezone'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'description' => 'getDescription',
        'initial_delay' => 'getInitialDelay',
        'timeout_in_mins' => 'getTimeoutInMins',
        'voices' => 'getVoices',
        'dictionaries' => 'getDictionaries',
        'config' => 'getConfig',
        'source_stream' => 'getSourceStream',
        'target_streams' => 'getTargetStreams',
        'start_time' => 'getStartTime',
        'end_time' => 'getEndTime',
        'timezone' => 'getTimezone'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('initial_delay', $data ?? [], 120);
        $this->setIfExists('timeout_in_mins', $data ?? [], null);
        $this->setIfExists('voices', $data ?? [], null);
        $this->setIfExists('dictionaries', $data ?? [], null);
        $this->setIfExists('config', $data ?? [], null);
        $this->setIfExists('source_stream', $data ?? [], null);
        $this->setIfExists('target_streams', $data ?? [], null);
        $this->setIfExists('start_time', $data ?? [], null);
        $this->setIfExists('end_time', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['voices'] === null) {
            $invalidProperties[] = "'voices' can't be null";
        }
        if ((count($this->container['voices']) > 1)) {
            $invalidProperties[] = "invalid value for 'voices', number of items must be less than or equal to 1.";
        }

        if ((count($this->container['voices']) < 0)) {
            $invalidProperties[] = "invalid value for 'voices', number of items must be greater than or equal to 0.";
        }

        if ($this->container['dictionaries'] === null) {
            $invalidProperties[] = "'dictionaries' can't be null";
        }
        if ((count($this->container['dictionaries']) > 5)) {
            $invalidProperties[] = "invalid value for 'dictionaries', number of items must be less than or equal to 5.";
        }

        if ((count($this->container['dictionaries']) < 0)) {
            $invalidProperties[] = "invalid value for 'dictionaries', number of items must be greater than or equal to 0.";
        }

        if ($this->container['config'] === null) {
            $invalidProperties[] = "'config' can't be null";
        }
        if ($this->container['source_stream'] === null) {
            $invalidProperties[] = "'source_stream' can't be null";
        }
        if ($this->container['target_streams'] === null) {
            $invalidProperties[] = "'target_streams' can't be null";
        }
        if ((count($this->container['target_streams']) < 1)) {
            $invalidProperties[] = "invalid value for 'target_streams', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets initial_delay
     *
     * @return int|null
     */
    public function getInitialDelay()
    {
        return $this->container['initial_delay'];
    }

    /**
     * Sets initial_delay
     *
     * @param int|null $initial_delay The initial delay in seconds before starting the stream creation process.
     *
     * @return self
     */
    public function setInitialDelay($initial_delay)
    {
        if (is_null($initial_delay)) {
            throw new \InvalidArgumentException('non-nullable initial_delay cannot be null');
        }
        $this->container['initial_delay'] = $initial_delay;

        return $this;
    }

    /**
     * Gets timeout_in_mins
     *
     * @return int|null
     */
    public function getTimeoutInMins()
    {
        return $this->container['timeout_in_mins'];
    }

    /**
     * Sets timeout_in_mins
     *
     * @param int|null $timeout_in_mins timeout_in_mins
     *
     * @return self
     */
    public function setTimeoutInMins($timeout_in_mins)
    {
        if (is_null($timeout_in_mins)) {
            array_push($this->openAPINullablesSetToNull, 'timeout_in_mins');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('timeout_in_mins', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['timeout_in_mins'] = $timeout_in_mins;

        return $this;
    }

    /**
     * Gets voices
     *
     * @return int[]
     */
    public function getVoices()
    {
        return $this->container['voices'];
    }

    /**
     * Sets voices
     *
     * @param int[] $voices List of voice identifiers to be used in the stream.
     *
     * @return self
     */
    public function setVoices($voices)
    {
        if (is_null($voices)) {
            throw new \InvalidArgumentException('non-nullable voices cannot be null');
        }

        if ((count($voices) > 1)) {
            throw new \InvalidArgumentException('invalid value for $voices when calling CreateStreamRequestPayload., number of items must be less than or equal to 1.');
        }
        if ((count($voices) < 0)) {
            throw new \InvalidArgumentException('invalid length for $voices when calling CreateStreamRequestPayload., number of items must be greater than or equal to 0.');
        }
        $this->container['voices'] = $voices;

        return $this;
    }

    /**
     * Gets dictionaries
     *
     * @return int[]
     */
    public function getDictionaries()
    {
        return $this->container['dictionaries'];
    }

    /**
     * Sets dictionaries
     *
     * @param int[] $dictionaries List of dictionary identifiers to be used in the stream.
     *
     * @return self
     */
    public function setDictionaries($dictionaries)
    {
        if (is_null($dictionaries)) {
            throw new \InvalidArgumentException('non-nullable dictionaries cannot be null');
        }

        if ((count($dictionaries) > 5)) {
            throw new \InvalidArgumentException('invalid value for $dictionaries when calling CreateStreamRequestPayload., number of items must be less than or equal to 5.');
        }
        if ((count($dictionaries) < 0)) {
            throw new \InvalidArgumentException('invalid length for $dictionaries when calling CreateStreamRequestPayload., number of items must be greater than or equal to 0.');
        }
        $this->container['dictionaries'] = $dictionaries;

        return $this;
    }

    /**
     * Gets config
     *
     * @return \Camb.ai\Model\ConfigStream
     */
    public function getConfig()
    {
        return $this->container['config'];
    }

    /**
     * Sets config
     *
     * @param \Camb.ai\Model\ConfigStream $config The shared configuration for the streaming pipeline.
     *
     * @return self
     */
    public function setConfig($config)
    {
        if (is_null($config)) {
            throw new \InvalidArgumentException('non-nullable config cannot be null');
        }
        $this->container['config'] = $config;

        return $this;
    }

    /**
     * Gets source_stream
     *
     * @return \Camb.ai\Model\SourceStream
     */
    public function getSourceStream()
    {
        return $this->container['source_stream'];
    }

    /**
     * Sets source_stream
     *
     * @param \Camb.ai\Model\SourceStream $source_stream The source stream configuration details.
     *
     * @return self
     */
    public function setSourceStream($source_stream)
    {
        if (is_null($source_stream)) {
            throw new \InvalidArgumentException('non-nullable source_stream cannot be null');
        }
        $this->container['source_stream'] = $source_stream;

        return $this;
    }

    /**
     * Gets target_streams
     *
     * @return \Camb.ai\Model\TargetStream[]
     */
    public function getTargetStreams()
    {
        return $this->container['target_streams'];
    }

    /**
     * Sets target_streams
     *
     * @param \Camb.ai\Model\TargetStream[] $target_streams List of target stream configurations.
     *
     * @return self
     */
    public function setTargetStreams($target_streams)
    {
        if (is_null($target_streams)) {
            throw new \InvalidArgumentException('non-nullable target_streams cannot be null');
        }


        if ((count($target_streams) < 1)) {
            throw new \InvalidArgumentException('invalid length for $target_streams when calling CreateStreamRequestPayload., number of items must be greater than or equal to 1.');
        }
        $this->container['target_streams'] = $target_streams;

        return $this;
    }

    /**
     * Gets start_time
     *
     * @return \DateTime|null
     */
    public function getStartTime()
    {
        return $this->container['start_time'];
    }

    /**
     * Sets start_time
     *
     * @param \DateTime|null $start_time start_time
     *
     * @return self
     */
    public function setStartTime($start_time)
    {
        if (is_null($start_time)) {
            array_push($this->openAPINullablesSetToNull, 'start_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('start_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['start_time'] = $start_time;

        return $this;
    }

    /**
     * Gets end_time
     *
     * @return \DateTime|null
     */
    public function getEndTime()
    {
        return $this->container['end_time'];
    }

    /**
     * Sets end_time
     *
     * @param \DateTime|null $end_time end_time
     *
     * @return self
     */
    public function setEndTime($end_time)
    {
        if (is_null($end_time)) {
            array_push($this->openAPINullablesSetToNull, 'end_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['end_time'] = $end_time;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string|null
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string|null $timezone timezone
     *
     * @return self
     */
    public function setTimezone($timezone)
    {
        if (is_null($timezone)) {
            array_push($this->openAPINullablesSetToNull, 'timezone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('timezone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


