<?php
/**
 * SourceStream
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Camb\Ai\Model;

use \ArrayAccess;
use \Camb\Ai\ObjectSerializer;

/**
 * SourceStream Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SourceStream implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SourceStream';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'language' => '\Camb.ai\Model\Languages',
        'url' => 'string',
        'category' => '\Camb.ai\Model\StreamCategory',
        'passphrase' => 'string',
        'streamid' => 'string',
        'number_of_streams' => 'int',
        'audio_stream' => 'int',
        'background_audio_stream' => 'int',
        'latency' => 'int',
        'relay_input' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'language' => null,
        'url' => null,
        'category' => null,
        'passphrase' => null,
        'streamid' => null,
        'number_of_streams' => null,
        'audio_stream' => null,
        'background_audio_stream' => null,
        'latency' => null,
        'relay_input' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'language' => false,
        'url' => false,
        'category' => true,
        'passphrase' => true,
        'streamid' => true,
        'number_of_streams' => true,
        'audio_stream' => true,
        'background_audio_stream' => true,
        'latency' => true,
        'relay_input' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'language' => 'language',
        'url' => 'url',
        'category' => 'category',
        'passphrase' => 'passphrase',
        'streamid' => 'streamid',
        'number_of_streams' => 'number_of_streams',
        'audio_stream' => 'audio_stream',
        'background_audio_stream' => 'background_audio_stream',
        'latency' => 'latency',
        'relay_input' => 'relay_input'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'language' => 'setLanguage',
        'url' => 'setUrl',
        'category' => 'setCategory',
        'passphrase' => 'setPassphrase',
        'streamid' => 'setStreamid',
        'number_of_streams' => 'setNumberOfStreams',
        'audio_stream' => 'setAudioStream',
        'background_audio_stream' => 'setBackgroundAudioStream',
        'latency' => 'setLatency',
        'relay_input' => 'setRelayInput'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'language' => 'getLanguage',
        'url' => 'getUrl',
        'category' => 'getCategory',
        'passphrase' => 'getPassphrase',
        'streamid' => 'getStreamid',
        'number_of_streams' => 'getNumberOfStreams',
        'audio_stream' => 'getAudioStream',
        'background_audio_stream' => 'getBackgroundAudioStream',
        'latency' => 'getLatency',
        'relay_input' => 'getRelayInput'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('category', $data ?? [], null);
        $this->setIfExists('passphrase', $data ?? [], null);
        $this->setIfExists('streamid', $data ?? [], null);
        $this->setIfExists('number_of_streams', $data ?? [], null);
        $this->setIfExists('audio_stream', $data ?? [], null);
        $this->setIfExists('background_audio_stream', $data ?? [], null);
        $this->setIfExists('latency', $data ?? [], null);
        $this->setIfExists('relay_input', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['language'] === null) {
            $invalidProperties[] = "'language' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets language
     *
     * @return \Camb.ai\Model\Languages
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param \Camb.ai\Model\Languages $language language
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets category
     *
     * @return \Camb.ai\Model\StreamCategory|null
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param \Camb.ai\Model\StreamCategory|null $category category
     *
     * @return self
     */
    public function setCategory($category)
    {
        if (is_null($category)) {
            array_push($this->openAPINullablesSetToNull, 'category');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('category', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets passphrase
     *
     * @return string|null
     */
    public function getPassphrase()
    {
        return $this->container['passphrase'];
    }

    /**
     * Sets passphrase
     *
     * @param string|null $passphrase passphrase
     *
     * @return self
     */
    public function setPassphrase($passphrase)
    {
        if (is_null($passphrase)) {
            array_push($this->openAPINullablesSetToNull, 'passphrase');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('passphrase', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['passphrase'] = $passphrase;

        return $this;
    }

    /**
     * Gets streamid
     *
     * @return string|null
     */
    public function getStreamid()
    {
        return $this->container['streamid'];
    }

    /**
     * Sets streamid
     *
     * @param string|null $streamid streamid
     *
     * @return self
     */
    public function setStreamid($streamid)
    {
        if (is_null($streamid)) {
            array_push($this->openAPINullablesSetToNull, 'streamid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('streamid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['streamid'] = $streamid;

        return $this;
    }

    /**
     * Gets number_of_streams
     *
     * @return int|null
     */
    public function getNumberOfStreams()
    {
        return $this->container['number_of_streams'];
    }

    /**
     * Sets number_of_streams
     *
     * @param int|null $number_of_streams number_of_streams
     *
     * @return self
     */
    public function setNumberOfStreams($number_of_streams)
    {
        if (is_null($number_of_streams)) {
            array_push($this->openAPINullablesSetToNull, 'number_of_streams');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('number_of_streams', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['number_of_streams'] = $number_of_streams;

        return $this;
    }

    /**
     * Gets audio_stream
     *
     * @return int|null
     */
    public function getAudioStream()
    {
        return $this->container['audio_stream'];
    }

    /**
     * Sets audio_stream
     *
     * @param int|null $audio_stream audio_stream
     *
     * @return self
     */
    public function setAudioStream($audio_stream)
    {
        if (is_null($audio_stream)) {
            array_push($this->openAPINullablesSetToNull, 'audio_stream');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('audio_stream', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['audio_stream'] = $audio_stream;

        return $this;
    }

    /**
     * Gets background_audio_stream
     *
     * @return int|null
     */
    public function getBackgroundAudioStream()
    {
        return $this->container['background_audio_stream'];
    }

    /**
     * Sets background_audio_stream
     *
     * @param int|null $background_audio_stream background_audio_stream
     *
     * @return self
     */
    public function setBackgroundAudioStream($background_audio_stream)
    {
        if (is_null($background_audio_stream)) {
            array_push($this->openAPINullablesSetToNull, 'background_audio_stream');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('background_audio_stream', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['background_audio_stream'] = $background_audio_stream;

        return $this;
    }

    /**
     * Gets latency
     *
     * @return int|null
     */
    public function getLatency()
    {
        return $this->container['latency'];
    }

    /**
     * Sets latency
     *
     * @param int|null $latency latency
     *
     * @return self
     */
    public function setLatency($latency)
    {
        if (is_null($latency)) {
            array_push($this->openAPINullablesSetToNull, 'latency');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('latency', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['latency'] = $latency;

        return $this;
    }

    /**
     * Gets relay_input
     *
     * @return bool|null
     */
    public function getRelayInput()
    {
        return $this->container['relay_input'];
    }

    /**
     * Sets relay_input
     *
     * @param bool|null $relay_input relay_input
     *
     * @return self
     */
    public function setRelayInput($relay_input)
    {
        if (is_null($relay_input)) {
            array_push($this->openAPINullablesSetToNull, 'relay_input');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('relay_input', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['relay_input'] = $relay_input;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


