<?php
/**
 * TargetStream
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Camb\Ai\Model;

use \ArrayAccess;
use \Camb\Ai\ObjectSerializer;

/**
 * TargetStream Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TargetStream implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TargetStream';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'languages' => '\Camb.ai\Model\Languages[]',
        'url' => 'string',
        'type' => '\Camb.ai\Model\StreamType',
        'passphrase' => 'string',
        'streamid' => 'string',
        'pids' => 'int[]',
        'transcode_video' => 'bool',
        'embed_subtitles' => 'bool',
        'audio_codec' => 'string',
        'audio_bitrate' => 'string',
        'audio_channel_layout' => 'string',
        'latency' => 'int',
        'constant_bitrate' => 'bool',
        'relay_output' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'languages' => null,
        'url' => null,
        'type' => null,
        'passphrase' => null,
        'streamid' => null,
        'pids' => null,
        'transcode_video' => null,
        'embed_subtitles' => null,
        'audio_codec' => null,
        'audio_bitrate' => null,
        'audio_channel_layout' => null,
        'latency' => null,
        'constant_bitrate' => null,
        'relay_output' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'languages' => false,
        'url' => false,
        'type' => false,
        'passphrase' => true,
        'streamid' => true,
        'pids' => true,
        'transcode_video' => true,
        'embed_subtitles' => true,
        'audio_codec' => true,
        'audio_bitrate' => true,
        'audio_channel_layout' => true,
        'latency' => true,
        'constant_bitrate' => true,
        'relay_output' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'languages' => 'languages',
        'url' => 'url',
        'type' => 'type',
        'passphrase' => 'passphrase',
        'streamid' => 'streamid',
        'pids' => 'pids',
        'transcode_video' => 'transcode_video',
        'embed_subtitles' => 'embed_subtitles',
        'audio_codec' => 'audio_codec',
        'audio_bitrate' => 'audio_bitrate',
        'audio_channel_layout' => 'audio_channel_layout',
        'latency' => 'latency',
        'constant_bitrate' => 'constant_bitrate',
        'relay_output' => 'relay_output'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'languages' => 'setLanguages',
        'url' => 'setUrl',
        'type' => 'setType',
        'passphrase' => 'setPassphrase',
        'streamid' => 'setStreamid',
        'pids' => 'setPids',
        'transcode_video' => 'setTranscodeVideo',
        'embed_subtitles' => 'setEmbedSubtitles',
        'audio_codec' => 'setAudioCodec',
        'audio_bitrate' => 'setAudioBitrate',
        'audio_channel_layout' => 'setAudioChannelLayout',
        'latency' => 'setLatency',
        'constant_bitrate' => 'setConstantBitrate',
        'relay_output' => 'setRelayOutput'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'languages' => 'getLanguages',
        'url' => 'getUrl',
        'type' => 'getType',
        'passphrase' => 'getPassphrase',
        'streamid' => 'getStreamid',
        'pids' => 'getPids',
        'transcode_video' => 'getTranscodeVideo',
        'embed_subtitles' => 'getEmbedSubtitles',
        'audio_codec' => 'getAudioCodec',
        'audio_bitrate' => 'getAudioBitrate',
        'audio_channel_layout' => 'getAudioChannelLayout',
        'latency' => 'getLatency',
        'constant_bitrate' => 'getConstantBitrate',
        'relay_output' => 'getRelayOutput'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('languages', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('passphrase', $data ?? [], null);
        $this->setIfExists('streamid', $data ?? [], null);
        $this->setIfExists('pids', $data ?? [], null);
        $this->setIfExists('transcode_video', $data ?? [], null);
        $this->setIfExists('embed_subtitles', $data ?? [], null);
        $this->setIfExists('audio_codec', $data ?? [], null);
        $this->setIfExists('audio_bitrate', $data ?? [], null);
        $this->setIfExists('audio_channel_layout', $data ?? [], null);
        $this->setIfExists('latency', $data ?? [], null);
        $this->setIfExists('constant_bitrate', $data ?? [], null);
        $this->setIfExists('relay_output', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['languages'] === null) {
            $invalidProperties[] = "'languages' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets languages
     *
     * @return \Camb.ai\Model\Languages[]
     */
    public function getLanguages()
    {
        return $this->container['languages'];
    }

    /**
     * Sets languages
     *
     * @param \Camb.ai\Model\Languages[] $languages languages
     *
     * @return self
     */
    public function setLanguages($languages)
    {
        if (is_null($languages)) {
            throw new \InvalidArgumentException('non-nullable languages cannot be null');
        }
        $this->container['languages'] = $languages;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \Camb.ai\Model\StreamType
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Camb.ai\Model\StreamType $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets passphrase
     *
     * @return string|null
     */
    public function getPassphrase()
    {
        return $this->container['passphrase'];
    }

    /**
     * Sets passphrase
     *
     * @param string|null $passphrase passphrase
     *
     * @return self
     */
    public function setPassphrase($passphrase)
    {
        if (is_null($passphrase)) {
            array_push($this->openAPINullablesSetToNull, 'passphrase');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('passphrase', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['passphrase'] = $passphrase;

        return $this;
    }

    /**
     * Gets streamid
     *
     * @return string|null
     */
    public function getStreamid()
    {
        return $this->container['streamid'];
    }

    /**
     * Sets streamid
     *
     * @param string|null $streamid streamid
     *
     * @return self
     */
    public function setStreamid($streamid)
    {
        if (is_null($streamid)) {
            array_push($this->openAPINullablesSetToNull, 'streamid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('streamid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['streamid'] = $streamid;

        return $this;
    }

    /**
     * Gets pids
     *
     * @return int[]|null
     */
    public function getPids()
    {
        return $this->container['pids'];
    }

    /**
     * Sets pids
     *
     * @param int[]|null $pids pids
     *
     * @return self
     */
    public function setPids($pids)
    {
        if (is_null($pids)) {
            array_push($this->openAPINullablesSetToNull, 'pids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pids'] = $pids;

        return $this;
    }

    /**
     * Gets transcode_video
     *
     * @return bool|null
     */
    public function getTranscodeVideo()
    {
        return $this->container['transcode_video'];
    }

    /**
     * Sets transcode_video
     *
     * @param bool|null $transcode_video transcode_video
     *
     * @return self
     */
    public function setTranscodeVideo($transcode_video)
    {
        if (is_null($transcode_video)) {
            array_push($this->openAPINullablesSetToNull, 'transcode_video');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('transcode_video', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['transcode_video'] = $transcode_video;

        return $this;
    }

    /**
     * Gets embed_subtitles
     *
     * @return bool|null
     */
    public function getEmbedSubtitles()
    {
        return $this->container['embed_subtitles'];
    }

    /**
     * Sets embed_subtitles
     *
     * @param bool|null $embed_subtitles embed_subtitles
     *
     * @return self
     */
    public function setEmbedSubtitles($embed_subtitles)
    {
        if (is_null($embed_subtitles)) {
            array_push($this->openAPINullablesSetToNull, 'embed_subtitles');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('embed_subtitles', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['embed_subtitles'] = $embed_subtitles;

        return $this;
    }

    /**
     * Gets audio_codec
     *
     * @return string|null
     */
    public function getAudioCodec()
    {
        return $this->container['audio_codec'];
    }

    /**
     * Sets audio_codec
     *
     * @param string|null $audio_codec audio_codec
     *
     * @return self
     */
    public function setAudioCodec($audio_codec)
    {
        if (is_null($audio_codec)) {
            array_push($this->openAPINullablesSetToNull, 'audio_codec');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('audio_codec', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['audio_codec'] = $audio_codec;

        return $this;
    }

    /**
     * Gets audio_bitrate
     *
     * @return string|null
     */
    public function getAudioBitrate()
    {
        return $this->container['audio_bitrate'];
    }

    /**
     * Sets audio_bitrate
     *
     * @param string|null $audio_bitrate audio_bitrate
     *
     * @return self
     */
    public function setAudioBitrate($audio_bitrate)
    {
        if (is_null($audio_bitrate)) {
            array_push($this->openAPINullablesSetToNull, 'audio_bitrate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('audio_bitrate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['audio_bitrate'] = $audio_bitrate;

        return $this;
    }

    /**
     * Gets audio_channel_layout
     *
     * @return string|null
     */
    public function getAudioChannelLayout()
    {
        return $this->container['audio_channel_layout'];
    }

    /**
     * Sets audio_channel_layout
     *
     * @param string|null $audio_channel_layout audio_channel_layout
     *
     * @return self
     */
    public function setAudioChannelLayout($audio_channel_layout)
    {
        if (is_null($audio_channel_layout)) {
            array_push($this->openAPINullablesSetToNull, 'audio_channel_layout');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('audio_channel_layout', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['audio_channel_layout'] = $audio_channel_layout;

        return $this;
    }

    /**
     * Gets latency
     *
     * @return int|null
     */
    public function getLatency()
    {
        return $this->container['latency'];
    }

    /**
     * Sets latency
     *
     * @param int|null $latency latency
     *
     * @return self
     */
    public function setLatency($latency)
    {
        if (is_null($latency)) {
            array_push($this->openAPINullablesSetToNull, 'latency');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('latency', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['latency'] = $latency;

        return $this;
    }

    /**
     * Gets constant_bitrate
     *
     * @return bool|null
     */
    public function getConstantBitrate()
    {
        return $this->container['constant_bitrate'];
    }

    /**
     * Sets constant_bitrate
     *
     * @param bool|null $constant_bitrate constant_bitrate
     *
     * @return self
     */
    public function setConstantBitrate($constant_bitrate)
    {
        if (is_null($constant_bitrate)) {
            array_push($this->openAPINullablesSetToNull, 'constant_bitrate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('constant_bitrate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['constant_bitrate'] = $constant_bitrate;

        return $this;
    }

    /**
     * Gets relay_output
     *
     * @return bool|null
     */
    public function getRelayOutput()
    {
        return $this->container['relay_output'];
    }

    /**
     * Sets relay_output
     *
     * @param bool|null $relay_output relay_output
     *
     * @return self
     */
    public function setRelayOutput($relay_output)
    {
        if (is_null($relay_output)) {
            array_push($this->openAPINullablesSetToNull, 'relay_output');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('relay_output', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['relay_output'] = $relay_output;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


