<?php
/**
 * TranscriptFileFormat
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Camb\Ai\Model;
use \Camb\Ai\ObjectSerializer;

/**
 * TranscriptFileFormat Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TranscriptFileFormat
{
    /**
     * Possible values of this enum
     */
    public const SRT = 'srt';

    public const VTT = 'vtt';

    public const TXT = 'txt';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SRT,
            self::VTT,
            self::TXT
        ];
    }
}


