<?php
/**
 * DubbedOutputInAltFormatRequestPayloadTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Camb.ai\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DubbedOutputInAltFormatRequestPayloadTest Class Doc Comment
 *
 * @category    Class
 * @description DubbedOutputInAltFormatRequestPayload
 * @package     Camb.ai
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DubbedOutputInAltFormatRequestPayloadTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DubbedOutputInAltFormatRequestPayload"
     */
    public function testDubbedOutputInAltFormatRequestPayload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "output_format"
     */
    public function testPropertyOutputFormat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
