<?php
/**
 * StoryDetailsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Camb.ai\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * StoryDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description StoryDetails
 * @package     Camb.ai
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class StoryDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StoryDetails"
     */
    public function testStoryDetails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "story_title"
     */
    public function testPropertyStoryTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "story_description"
     */
    public function testPropertyStoryDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "source_language"
     */
    public function testPropertySourceLanguage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "target_languages"
     */
    public function testPropertyTargetLanguages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "folder_id"
     */
    public function testPropertyFolderId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "studio_url"
     */
    public function testPropertyStudioUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
