<?php
/**
 * StreamTTSVoiceSettingsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Camb.ai\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * StreamTTSVoiceSettingsTest Class Doc Comment
 *
 * @category    Class
 * @description Advanced settings for voice customization.  Attributes:     enhance_reference_audio_quality: Whether to enhance the quality of the         reference audio before cloning. Defaults to False.
 * @package     Camb.ai
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class StreamTTSVoiceSettingsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StreamTTSVoiceSettings"
     */
    public function testStreamTTSVoiceSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "enhance_reference_audio_quality"
     */
    public function testPropertyEnhanceReferenceAudioQuality()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "maintain_source_accent"
     */
    public function testPropertyMaintainSourceAccent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
