<?php
/**
 * TextToSpeechApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Camb.ai\Test\Api;

use \Camb.ai\Configuration;
use \Camb.ai\ApiException;
use \Camb.ai\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TextToSpeechApiTest Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TextToSpeechApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createTtsTtsPost
     *
     * Create Tts.
     *
     */
    public function testCreateTtsTtsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTtsResultDiscordDiscordTtsTaskIdGet
     *
     * Get Tts Result Discord.
     *
     */
    public function testGetTtsResultDiscordDiscordTtsTaskIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTtsResultTtsTaskIdGet
     *
     * Get Tts Result.
     *
     */
    public function testGetTtsResultTtsTaskIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTtsResultsTtsResultsPost
     *
     * Get Tts Results.
     *
     */
    public function testGetTtsResultsTtsResultsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTtsRunInfoTtsResultRunIdGet
     *
     * Get Tts Run Info.
     *
     */
    public function testGetTtsRunInfoTtsResultRunIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ttsTtsStreamPost
     *
     * Tts.
     *
     */
    public function testTtsTtsStreamPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
