<?php
/**
 * TranslationApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Camb.ai\Test\Api;

use \Camb.ai\Configuration;
use \Camb.ai\ApiException;
use \Camb.ai\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TranslationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TranslationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createTranslationTranslatePost
     *
     * Create Translation.
     *
     */
    public function testCreateTranslationTranslatePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createTranslationTranslatePost_0
     *
     * Create Translation.
     *
     */
    public function testCreateTranslationTranslatePost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTranslationResultTranslationResultRunIdGet
     *
     * Get Translation Result.
     *
     */
    public function testGetTranslationResultTranslationResultRunIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTranslationResultTranslationResultRunIdGet_0
     *
     * Get Translation Result.
     *
     */
    public function testGetTranslationResultTranslationResultRunIdGet0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTranslationResultsTranslationResultsPost
     *
     * Get Translation Results.
     *
     */
    public function testGetTranslationResultsTranslationResultsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTranslationResultsTranslationResultsPost_0
     *
     * Get Translation Results.
     *
     */
    public function testGetTranslationResultsTranslationResultsPost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTranslationTaskStatusTranslateTaskIdGet
     *
     * Get Translation Task Status.
     *
     */
    public function testGetTranslationTaskStatusTranslateTaskIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTranslationTaskStatusTranslateTaskIdGet_0
     *
     * Get Translation Task Status.
     *
     */
    public function testGetTranslationTaskStatusTranslateTaskIdGet0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for translationStreamTranslationStreamPost
     *
     * Translation Stream.
     *
     */
    public function testTranslationStreamTranslationStreamPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for translationStreamTranslationStreamPost_0
     *
     * Translation Stream.
     *
     */
    public function testTranslationStreamTranslationStreamPost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
