<?php
/**
 * TranslatedStoriesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Camb.ai\Test\Api;

use \Camb.ai\Configuration;
use \Camb.ai\ApiException;
use \Camb.ai\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TranslatedStoriesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TranslatedStoriesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createTranslationForExistingStoryTranslatedStoryRunIdPost
     *
     * Create Translation For Existing Story.
     *
     */
    public function testCreateTranslationForExistingStoryTranslatedStoryRunIdPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTranslatedStoryRunInfoTranslatedStoryResultRunIdTargetLanguageGet
     *
     * Get Translated Story Run Info.
     *
     */
    public function testGetTranslatedStoryRunInfoTranslatedStoryResultRunIdTargetLanguageGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTranslatedStoryStatusTranslatedStoryTaskIdGet
     *
     * Get Translated Story Status.
     *
     */
    public function testGetTranslatedStoryStatusTranslatedStoryTaskIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
