<?php
/**
 * VoiceCloningApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Camb.ai\Test\Api;

use \Camb.ai\Configuration;
use \Camb.ai\ApiException;
use \Camb.ai\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * VoiceCloningApiTest Class Doc Comment
 *
 * @category Class
 * @package  Camb.ai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VoiceCloningApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createCustomVoiceCreateCustomVoicePost
     *
     * Create Custom Voice.
     *
     */
    public function testCreateCustomVoiceCreateCustomVoicePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCustomVoiceCreateCustomVoicePost_0
     *
     * Create Custom Voice.
     *
     */
    public function testCreateCustomVoiceCreateCustomVoicePost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listVoicesListVoicesGet
     *
     * List Voices.
     *
     */
    public function testListVoicesListVoicesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listVoicesListVoicesGet_0
     *
     * List Voices.
     *
     */
    public function testListVoicesListVoicesGet0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
